### ISSUE TITLE
In Comparasion Report>Details & Logs section we donot see the snapshots where it differs, is there any way to do this

### ISSUE THREAD

**Issue by rupjit09** [scenarioo/scenarioo#1041]
In Comparison Report>Details & Logs section we donot see the snapshots where it differs, is there any way to do this

In Comparison Report>Details & Logs section we can see written logs but not the snapshots how it differs, it will be really helpful since nontechnical persons in management are not really familiar with the terms like webelement and the technical logs printed in logs, they just want to see the snapshots how it differs. Is this possible, if yes please let me know how, i didnot got the tutorial on how this can be done.

**Comment by davidlahner** [comment]
Hi rupjit09,

The Details & Logs section is part of the Manage View and is just a reporting tool to show that the comparison worked.

To explore the documentation with the comparisons, you have to a comparison in the header and then browse the use cases to get to the a specific step where you can see the graphical differences side by side.
<img width="1058" alt="Scenarioo-Comparisons" src="https://user-images.githubusercontent.com/7665276/110125277-6dd98a00-7dc3-11eb-8559-aa915ce4fef5.png">

You can explore a working example on our demo server: http://demo.scenarioo.org/scenarioo-develop/#/step/Browse%20object%20details/Default%20expand%20and%20collapse/object_uiAction_example.action.StartInitAction/0/0

Further examples and information can be found in the documentation: http://scenarioo.org/docs/master/features/diff-viewer/diff-viewer.html

**Comment by rupjit09** [comment]
Thanks @eggerschwiler
