### ISSUE TITLE
Screen Annotations: graphically mark events and add other interessting annotations to Screenshots

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#149]
As a user of the scenarioo documentation I want to see important informations directly inside the screenshots as so called "screen annotations", such that I can see where the test interacted with the UI or other important informations that we want to highlight in the screenshots (e.g. caption/subtitle, URL the test entered or changed, click region, typed text, selection items inside a dropdown, mouse-over-texts, validated fields, etc.)

We identified the following important types of annotations so far, that we want to support with our design
* click events (button, checkbox, etc.)
* select event inside a combo-box or list
* typing inside a text box
* typing an URL in the browser navigation address bar
* pressing refresh / back / forward buttons in browser
* mark a field who's content was validated by the test (assertion)
* mark fields for additional informations about the fields (e.g. all selection items inside a combo box)
* any important text you want to put visually on the screenshot (any warning, or a caption/subtitle about what happens in this step)
* there might be more types of annotations we did not think of yet

In general the annotations are realized generically, such that any other information can be stored in a similar way. The design therefore consists of the possibility to place arbitrary rectangular regions as "screen annotations" on a step, with addtional informations like text and description and additional informations (as generic data structure as other details in scenarioo documentation format). Detailed format description see acceptance criterias and JSON example below.

#### Acceptance criteria

* The API (Java and C#) is extended such that multiple "screen annotations" can be added to a step. Each screenAnnotation consists of following informations (see also JSON example below):
  * region: rectangular area on the screen to highlight (x,y,width,height), origin of coordinates is the top left corner of the screenshot.
  * screenText (optional): a text to display inside the region directly on the screen (client will cut off the text if too long). The text is also displayed in popup (in full length, in any case).
  * title (optional): a title to display in the info popup on an annotation as bold title (if not set, 'screenText' is used as popup title, or 'description')
  * description (optional): A longer description text to only display inside the popup that appears when clicking on an annotation (below the other 'text' which is displayed as strong caption above the description text inside the popup)
  * style (optional, default="DEFAULT"): Determines, how the marked region is styled. One of several predefined styles: "CLICK" | "KEYBOARD" | "EXPECTED" | "NAVIGATE_TO_URL" | "WARN" | "ERROR" | "INFO" | "HIGHLIGHT" | "DEFAULT".
  * clickAction (optional): Determines what happens if the annotated region is clicked. One of "TO_NEXT_STEP" | "TO_URL". Default behaviour is to open the information popup.
  * clickActionUrl (optional): URL that is opened in case the clickAction is set to "TO_URL". (mandatory if clickAction is set to "TO_URL")
  * clickActionText (optional): information to be displayed as mouse over for an attached click action (if not avaialble a generic text "go to next page" or "open <url>" will be displayed.)
  * details (optional): Generic Metadata as everywhere else in Scenarioo. This is also displayed in the popup below the description (usual rendering as in metadata trees on other pages of Scenarioo).
* Whenever a step contains screen annotations, the Scenarioo client displays them in the correct position as an overlay on the screenshot (rectangular marker, icon dependent on style, text inside rectangular region).
* the regions are placed correctly over the screenshot in all supported browsers and are placed correctly depending on the size of the screenshot. 
* the "screenText" is displayed inside an annotation if available, if regions get to small the "screenText" will not appear anymore (user can still click to open the details popup to see it).
* each annotation has an icon in the upper right corner, that is different depending on its style (if no style is specified, "DEFAULT" is used)
* clicking on the icon of an annotation opens a popup to display information about the annotation (text, description, details)
    * the popup displays a title as bold text (property 'title' or "screenText" or otherwise the same as "description")
    * below the title the 'description' is displayed (if not allready same as title)    
    * if a clickAction is defined, it is displayed as a Link below the description (with text 'clickActionText' or a generic text)
    * all details are displayed (same as other metadata)
    * the popup is closed when clicking outside the popup 
    * the popup can be scrolled (if many details are contained, using browsers scroll bar)
* if no clickAction is specified, clicking the whole rectangular region has the same effect as clicking the image icon button to open the popup
* If a screen annotation has a defined clickAction
    * the region is clickable with the specified behaviour (go to next step, open a specified clickActionURL in new window). 
    * the annotation is styled as a special link with a mouse over tooltip that informs the user about the attached userAction (before clicking)
* button "show/hide annotations": user can choose to turn rendering of screen annotations on and off in the client on every step
    * this button is only displayed on steps that have annotations        
    * this setting is stored in local storage in the client, if a user turned it off, all annotatons will disappear, until the user turns it on again
* all objects stored in details of screen annotations are also stored in object repository and can therefore be retrieved (see new demo tab "UI Elements" on home page)

#### JSON structure on step object for the client

Only the "region" field is mandatory in the API.

	{
		"stepStatistics" : { ... },
		"stepIdentifier" : { ... },
		"fallback" : false,
		"step" : {
			"page" : { ... },
			"metadata" : { ... },
			"html" : { ... },
			"screenAnnotations" : [
				{
					region : {
						x: 123,
						y: 222,
						width: 222,
						height: 20					
					},
					screenText: "Blabla",
                                        title: "Title for Popup",
					description: "Bliblubb",
					style: "CLICK" | "KEYBOARD" | "EXPECTED" | "NAVIGATE_TO_URL" | "WARN" | "ERROR" | "INFO" | "HIGHLIGHT" | "DEFAULT",
					clickAction: "TO_NEXT_STEP" | "TO_URL",
					clickActionUrl: "http://...",
                                        clickActionText: "Open documentation 'XY'"
					details: {
						...
					}
				}
			],
			"stepDescription" : { ... }
		},
		"stepNavigation" : { ... },
		"useCaseLabels" : { ... },
		"scenarioLabels" : { ... }
	}

####  limitations (or smaller changes regarding the original design):
* all annotations are currently styled in same color (orange), only the icons are different between styles. also the text sizes are the same for all annotation styles, later we could improve this to make this customizable. The border color currently depends on whether the annotation has a clickAction or not.
* all annotations currently only support text without braking to more than one line (overflow of too long texts does not work properly otherwise, see https://css-tricks.com/almanac/properties/t/text-overflow/ ---> following described solution could help for that to work: http://www.mobify.com/blog/multiline-ellipsis-in-pure-css/ but I did not get this to work)
* there is no close button for the details dialog, user can close it by clicking outside the dialog

#### see also

This design also covers story #393 because it is generic and extendable enough to cover this additional possibility to add arbitrary annotations.

**Comment by bruderol** [comment]
As a kickoff for this story I reviewed the description and detailed it a little bit.

@adiherzog Thank you, the description was allready very good, as discussed together. I only precised some details (if you like, you can review again).

I added one open point, that I am not sure, if we really thought about this well enough. Can you please review this open point above. I think we should not invest too much in this "goToPreviousStep"-Feature, this is really not Prio-1. I think all the rest is well designed.

**Comment by bruderol** [comment]
Implementation detail:
We could enforce on the writer library and in the docu format that the elements "text", "details", "description" are required but can be empty. I think this would be the better design, because we not have to program the client so defensively and can simply assume that string properties are never undefined but contain empty text if not set by the docu writer user explicitly.

**Comment by bruderol** [comment]
I had to choose a different word for style "default" because "default" is a reserved wrd in Java and I can not use it as a name for an enum.
I used "neutral" instead.

**Comment by bruderol** [comment]
API is extended and dummy data is available on second step of each Find Page scenario (where search text is entered and search button is pressed).

see following extract from the data now delivered from the REST server in the step data:

```
             "screenAnnotations": [{
                    "details": {
                        "element": {
                            "details": {
                                "elementId": "searchField",
                                "info": "this is just an example to demonstrate that also screen annotations can have objects as detail data attached, e.g. the description of a ui element that was interacted with"
                            }, "name": "searchField", "type": "uiElement"
                        }
                    },
                    "text": "Scenarioo",
                    "style": "keyboard",
                    "clickAction": null,
                    "clickActionUrl": null,
                    "region": {"x": 580, "y": 463, "width": 162, "height": 24},
                    "description": "text 'Scenarioo' entered"
                }, {
                    "details": {
                        "element": {
                            "details": {
                                "elementId": "searchButton",
                                "info": "this is just an example to demonstrate that also screen annotations can have objects as detail data attached, e.g. the description of a ui element that was interacted with"
                            }, "name": "searchButton", "type": "uiElement"
                        }
                    },
                    "text": "click",
                    "style": "click",
                    "clickAction": null,
                    "clickActionUrl": null,
                    "region": {"x": 956, "y": 464, "width": 55, "height": 26},
                    "description": "on element with id='searchButton'"
                }]
```
We can add more annotations easily, if needed, just let me know what you need more.

@adiherzog 
Please review and use it for starting with the client side implementation:
Take care to resolve all dependencise with gradle correctly (new writer library snapshot version) and generate the test data new by running the scenarioo-docu-generator-example tests (I recommend to first delete the build folder inside (to make sure that you not have old test data, somehow this happened to me).

What is missing for the server side:
Objects inside the screen annotations are not yet registered and indexed in our object repository (this is my next task).

**Comment by bruderol** [comment]
Objects from screen annotations now are also stored in object repository.

Furthermore I added additional screen annotations for some clicked links to the dummy data.
Also all "click"-annotations now have a clickAction="toNextStep" for testing purpose (the keyboard annotations on the other hand have no clickAction defined!).

**Comment by bruderol** [comment]
@adiherzog I think, that everything is well prepared to start implementing the visualization of the screen annotations. Server is finished. writer library is extended (except for the clickAction="toPreviousStep", see open point in this issue description), dummy data is available with many screen annotations of type "click" and "keyboard". We can easily add some more screen annotations of other types to dummy data. Also the annotations can be found by browsing the new tab "UI Elements" from object repository :smile:

**Comment by adiherzog** [comment]
@bruderol I agree that "toPreviousStep" does not make sense at all. Thanks for finding this :-) I will remove it from the specification.

**Comment by bruderol** [comment]
@adiherzog 

cool :smile: thanks for agreeing

is the new style "neutral" instead of "default" (see comment above, because I designed this as an explicit enum inside the format) and all the rest of the interface and format design for you also appropriate? Would be great if you could review this quickly, I want to order the development of the C# version of this part as soon as possible.

Please comment here shortly, when you have reviewed this.Thank you.

**Comment by adiherzog** [comment]
@bruderol 

Thanks a lot for implementing the API changes! It already looks quite good. Nevertheless there are some things we should improve.

* We should definitely use uppercase names for all Java Enum constants (see http://docs.oracle.com/javase/tutorial/java/javaOO/enum.html). Then we can also use DEFAULT, as this is allowed then. I propose to put the actual values for the XML file as a field in the Enums. There we can then use camel case, as designed. This should be quite easy, see https://jaxb.java.net/nonav/jaxb20-fcs/docs/api/javax/xml/bind/annotation/XmlEnumValue.html.
* The region is currently not mandatory. This can probably be fixed by adding `@XmlElement(required = true)`. The XSD should have `minOccurs="0"` for this field. By the way. I think we should not make any other fields mandatory apart from the position. In the JavaScript frontend it does not make a difference whether we have to deal with "null" values or with "undefined" values.
* All `@XmlElement(nillable = false)` declarations can be removed, as this is the default anyway.

Then there are two points about the possible "style" values where I think we could improve a bit:

* "validate" is ambiguous (it's not immediately clear whether it's a validation made in the application under test or an assertion made by the test). Therefore I would rename this to "validatedByTest" or similar.
* I think "navigateToUrl" is a bit weird because the browser Bar is not actually shown on the screenshot. Do you still think we should keep this style? Is it required by your customer?

What's your opinion on these inputs?

**Comment by bruderol** [comment]
@adiherzog:
Feedback to your inputs:
1. enums: I agree that we should use XmlEnumValue and then keep the enum names capitalized (I was a bit lazy about this, we can then use "DEFAULT" again)
2. region: yes, region should be mandatory,
3. nillable: I will remove it (did not know that this is the default, sorry). 
4. fields with default values: In anyway (even if not enforced by the format) the mentioned values will never be null or undefined, because our java reader implementation reading the files on the server ensures they are never null (values that are missing in the xml are not set to null, instead the default is used when reading it) --> therefore you not have to check for undefined or null values in the client. I think it is better to use "offensive programming" in the client instead of defensively allways checking for undefined or null (which will never happen). The server is responsible for defining the default values to use when a value is missing (like that we have this better centralized in one place). This keeps the client more focused and more simple.
4. validated: I see your point  --> we have to think about a better naming.
5. navigateToUrl: Yes, I think that this is an important event, for which we should provide a special style. Because the browser bar is not visible on the screen, that is exactly why I think this style is important.

**Comment by bruderol** [comment]
@adiherzog:
I adjusted the scenarioo-java API and the XSD as discussed.
instead of VALIDATED style, I now use the style name EXPECTED, because it marks an expected state/content in the UI that is validated by the test.
default style is now "DEFAULT" (can never be null in client)

I also adjusted dummy test data, such that the regions should be now positioned correctly.

**Comment by bruderol** [comment]
unfortunately, there is a problem with mapping the Enum values also to the client according to XmlEnumValue. RestEasy does not take this into account when mapping to Json. therefore on client side for enum values (e.g. for ScreenAnnotaitonStyle), we receive now the names of the enums, as implemented in Java (uppercase). Since it was not possible to introduce special Jackson-Annotations on the enum without introducing additional dependencies in the writer library, that we do not want, I did not address this small issue for now, because I assume it is no problem, that we have to deal with slightly different style codes on the client side (uppercase as for the enum names in Java).

**Comment by bruderol** [comment]
First version of popup is finished.

What is still missing:
* click action (to next step or to url)
* different mouse cursor, for areas where click action or popup can be opened.
* recalculate image positions when hide metadata is clicked
* only show "hide annotations" button, if annotations are available
* test data for all styles
* maybe improve icons (??) and styles (??)
* e2e UI tests: for popup, hide annotations button and click actions

**Comment by adiherzog** [comment]
@bruderol About the enum values: We could just use the uppercase variant everywhere. Then it would at least be consistent.

**Comment by bruderol** [comment]
@adiherzog: Yes, that is true.
@tobiaszuercher What do you think. Are uppercase constants as values for "clickAction" and "style" okay for you? Shall we change this?

**Comment by bruderol** [comment]
@tobiaszuercher How are you making progress with the C# library? Can we release this change soon?

**Comment by bruderol** [comment]
the constants are now refactored to be also in XML in upper case. 
for ScreenAnnotationStyle: “CLICK”, “KEYBOARD”, “EXPECTED”, “NAVIGATE_TO_URL”, “ERROR”, “WARN”, “INFO”, “HIGHLIGHT”, “DEFAULT“
for ScreenAnnotationClickAction: “TO_NEXT_STEP”, “TO_URL”

@tobiaszuercher please refactor this in your code and any example files.

**Comment by bruderol** [comment]
updated the description above to reflect the current planned implementation, there have been some small changes to the original design (as described at the end of the description).

**Comment by bruderol** [comment]
I updated the description of the story once again.

Major changes:
 * annotation with click action now gets a tooltip
 * the text of the tooltip can be specified in new optional annotation field "clickActionText"
 * some cleanup of consistency/redundancy in the description

@tobiaszuercher can you please introduce this additional property (simple optional text field, no special rules) also in the C# library? Thank you.

**Comment by adiherzog** [comment]
@bruderol Do we really need a possibility to set a custom tooltip text? We could just have a calculated text in the tooltip depending on the value of `clickAction`:

* "TO_NEXT_STEP" -> "Go to next step"
* "TO_URL" -> "Go to URL <clickActionUrl>"

**Comment by bruderol** [comment]
@adiherzog 
tooltip text is allready implemented, it is of course automatically calculated (as proposed by you, if the field is not set)

**Comment by bruderol** [comment]
@adiherzog @tobiaszuercher 
I consider the annotations implementation in the webapp as done / finished (as described in the description above).
Please review and give feedback in case you find some bugs.

**Comment by adiherzog** [comment]
@bruderol Good news :-) I will review it tomorrow.

**Comment by tobiaszuercher** [comment]
@bruderol all ok for me! The c# writer library follows c# naming conventions and hides whatever format is in your xml. keep your java standards, thats fine for me.

**Comment by bruderol** [comment]
I consider this as done. Testing starts now with one project.

**Comment by bruderol** [comment]
Testing in projects was succesful. Everything ready for the release.
