### ISSUE TITLE
Configuration of different term to use for "usecase" in UI

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#157]
Usecase might be a term that your business or business engineers do use differently and does not fit into their mental model for using it in the scenarioo documentation as a term for structuring/grouping your test scenarios. Therefore it is important to make this term customizable in the UI.

Another story #111 is about to change it in general to the term "Feature", also in the API, because this is assumed to be a more generic term and the term "Feature" is also used in other testing language areas (e.g. in Cucumber) as top level entry point. 

But since we are not realy sure, whether "Feature" is a better term for most projects (especially not necessarily in the UI) it is much more important to have this customizable in the UI only. Therefore we prioritized this story here much higher, without changing it yet in the API (for now we keep "Usecase" there).

Acceptance criterias:

 * everywhere in the UI where currently the static text "usecase" or "use case" or "usecases" or "use cases" (some of them are wrong anyway) are used, configurable values are used instead, one in singular form (default is "usecase") one in plural form (default is "usecases")
 * the terms to use for "usecase" and usecases" instead can be changed in the configuration screen and are stored in the configuration.

**Comment by adiherzog** [comment]
I am more and more convinced that "Use Case" is exactly the right name for our top level objects. Therefore I propose to close this story. @bruderol Do you agree on that?

**Comment by bruderol** [comment]
yes, I agree.
This issue was a very project specific request. But today event his specific project can live with the term "use case", because it is indeed the correct term, I think too.
