### ISSUE TITLE
Run end to end tests in build / on CI

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#167]

**Comment by adiherzog** [comment]
e2e tests now run on the build server after each check in

**Comment by danielsuter** [comment]
Congrats! Will a scenarioo documentation also be created automatically?

**Comment by bruderol** [comment]
very very cool :+1: :+1: :smiley: 

@danielsuter the generation of the documentation and deploying it on a special scenarioo instance (e.g. "/scenarioo-self-docu") is the next planned task by @adiherzog - correct Adrian?

Also it is planned to execute addiitonal tests (hello-world example, selenium demo, SWT example etc.) on the CI server and deploy all this generated example documentations into the scenarioo demo.
