### ISSUE TITLE
Advanced search / full text search

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#18]
As a user I want to search in all content from one simple UI (as on google).

I want to search for following things:
- visible text on pages
- HTML source code
- use case / scenario names and descriptions
- called services
- all metadata

**Comment by adiherzog** [comment]
This will be implemented in the next few weeks by a project that needs this. Any ideas and inputs regarding the architecture, the design and the usage scenarios are welcome, just post them here.

**Comment by bruderol** [comment]
@adiherzog since we realised that, i put it to Release 3.0

Those acceptance criterias that are missing should be transformed to a new story, if not yet, and then we can probably close?

**Comment by adiherzog** [comment]
@bruderol I close this as the basic feature is in place.
