### ISSUE TITLE
REST Service providing page information

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo#182]
Request from a customer:

A resource is needed which provides all variants of a page. The supplied parameters are the build name (aliases must be supported e.g. 'most recent') and the page name.

The result is an array containing all variants of a page with the given information:
* page name
* scenario
* link to screenshot
* link to step

This issue can only be completed if issue #166 is fixed first.

**Comment by adiherzog** [comment]
I close this as @danielsuter does not work for the project in question anymore.
