### ISSUE TITLE
Build script to run webtests and generate scenarioo documentation

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#258]
As a developer of the scenarioo-selenium-demo and as a course pariticipant playing with this example I want to have a simple script I can start to run the UI tests together with docu generation and finally deploying this generated docu (including the refresh service call) to the scenarioo web app.

Acceptance criterias
* There is a simple script to use to run all UI tests including generation of scenarioo
* a new directory for the build is created inside which the docu is written
* build.xml is also created inside this directory.
* servcie call to import the build inside local running scenarioo webapp is triggered

**Comment by bruderol** [comment]
@adiherzog I assuemd, that this story is about running the scenarioo-selenium-demo webtests, that's why I added this to our mini camp topic milestone. You should probably plan a similar story for running the Scenarioo e2e tests with generated scenarioo docu.

Maybe this is a topic where our both topics have some intersection and we can help each other. We will see.

**Comment by danielsuter** [comment]
This is already possible using gradle test, since we do everything in java using shut down hooks.

What could think of is making scenarioo configurable.

**Comment by adiherzog** [comment]
@bruderol @danielsuter What exactly is this story about? Is it about a script for running the webtests locally?

Then it would probably do about the following:

* Stop tomcat
* Copy the correct config so that we have a clean starting point for the tests
* Start tomcat
* Run `gulp serve`
* Run `gulp test-e2e-scenarioo`

I don't think that we need a script for this. But if somebody thinks its useful he can create it and contribute it to the project.

**Comment by bruderol** [comment]
This story is very bad written, sorry.
I do not know exactly what was the purpose of this issue was, but i assume that it was only concerned with the scenarioo-selenium-demo for courses. The idea was to have a script to locally run the demo tests together with scenarioo generation and then have this docu deployed to the locally running scenarioo webapp (restart of tomcat should not be needed for this!!!).

**Comment by bruderol** [comment]
Hab jetzt die beschreibung präzisiert, da hat der kontext gefehlt.
Vermutlich ist diese Story fast schon erledigt, siehe Kommentar von @danielsuter

**Comment by adiherzog** [comment]
Ah, now I get it. I moved it to the issue scenarioo-selenium-demo repository and will close this one here. We once agreed to only have the "Scenarioo Viewer" (that's the official name of the client now) issues here.

**Comment by bruderol** [comment]
@adiherzog yes, correct, thank you.
