### ISSUE TITLE
Use Vagrant for development environment

### ISSUE THREAD

**Issue by forkch** [scenarioo/scenarioo#279]
Use Vagrant to setup and maintain a consistent, versioned development environment with
- tomcat
- node
- grunt

Each developer may use its host system of choice for actual development but servers are running inside vagrant.

**Comment by bruderol** [comment]
@adiherzog @danielsuter I close this snce very old and I currently not see any urgent need. Our dev env is quite easy to setup and more or less well described, and everybody can install it like he likes to work. If anybody wants to do it we can still open a new issue.
