### ISSUE TITLE
Use default branch / build if the branch / build specified in the URL can't be found

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#294]
This requirement arises from a bug in Lync 2010 which encodes the & character in URLs to %26 and therefore makes the branch / build parameters useless.

See also my comment to this forum entry: http://social.technet.microsoft.com/Forums/lync/en-US/2b012640-4ff5-4273-bb11-5596274b9abb/lync-converts-urls-containing-with-26-creating-an-invalid-url-for-use-in-chrome

Acceptance criteria:
- Show a message, that the supplied branch / build parameters could not be found (Important, because the user might not be aware the the branch / build specification in the URL was invalid).
- Select the default branch / build instead.

**Comment by bruderol** [comment]
@adiherzog 2 years old and not done - still needed?? Not really a scenarioo problem. I think we can close. Ok?
