### ISSUE TITLE
Use a dependency injection framework in the Java server

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#296]
We could start using a DI framework like Google Guice on the server side. It's quite low priority, therefore I assign it to "Prio 2".

**Comment by mi-we** [comment]
I discussed recently with @adhierzog about the use of dependency injection. I think in regard of future functionality it might really be a good idea to have this. Basically I would have used CDI because it is already there but I also researched a bit about Dagger and it looks quite interesting.

**Comment by bruderol** [comment]
I personally that we can close the his topic now that we have spring in the backend and can use it where appropriate. But also I dont see big need to do much more DI than currently in the backend. @adiherzog @mi-we do you agree to close this?

**Comment by mi-we** [comment]
@bruderol Fine for me
