### ISSUE TITLE
Consequently encode identifiers in URLs

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#323]
Currently, some things are URL encoded (e.g. page name in step URL) and some are not (e.g. use case name in step URL). This should be changed so that all URL values going to the Server are always URL encoded.

**Comment by bruderol** [comment]
@adiherzog What is the state with this? We have to clean up our backlog, it gets bigger and bigger ...

**Comment by adiherzog** [comment]
I close this as there are no issue reports regarding this so we can assume that it works well enough.
