### ISSUE TITLE
Disallow slashes in C# API

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#325]
As a solution for issue #287 slashes and backslashes are disallowed in the C# API.

**Comment by adiherzog** [comment]
Moved issue to Scenarioo-CS repo (see scenarioo/scenarioo-cs#9)

**Comment by tobiaszuercher** [comment]
You had bigger discussions about this topic, but from a c# point of view this is a simple breaking change.

I don't like to break things without a warning or a chance for the user to adapt.

Anyway, i'll start to implement it.

**Comment by bruderol** [comment]
hmm, this is really a breaking change - didn't we once define to sanitize it and bring up a warning instead of blocking? what does the Java library do?
