### ISSUE TITLE
Introduce Google Guava for API

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#336]
We should use Google's Preconditions class for precondition checks in the API.
See class Preconditions in API, that can be replaced.

I added a TODO for this issue there.

Did not want to introduce a new dependency into the API so short before the release.

@adiherzog @danielsuter 
Can you check if this dependency would be a problem for some of your projects where scenarioo is used?

**Comment by bruderol** [comment]
I do not see a big need for this, as the current solution causes no problems. I considered this issue during our Coding Days, and then decided to leave the preconditions checks as they are currently implemented because I not want to introduce more dependencies for such simple things. Therefore I propose to close this.

@adiherzog @danielsuter what you think? agree with closing?

**Comment by adiherzog** [comment]
Yes we can close this.

**Comment by danielsuter** [comment]
I agree. I guess our next step would be java 8. So we could use the new capabilities there.

**Comment by bruderol** [comment]
:+1: Thanks for agreeing.
