### ISSUE TITLE
Can not select allready selected item in branch and build selection

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#342]
When selecting the build that is currently allready selected, nothing happens.
One could say this is a feature and not a bug ... but to the user this is very strange, because the currently selected build or branch is not styled as "disabled", therefore a user will expect, that something happens, when clicking on it.

**Acceptance criteria**
  * either the currently selected build/branch is specially highlighted¨as kind of "disabled because currently allready selected" in the dropdown list, or a user can select this item as the other items (I would prefer the second: do not suppress selection of allready selected item, as this is usual drop down behaviour a  user is expecting)

To be solved in #383 (is a duplicate of this for planning it to be resolved in another milestone).

**Comment by adiherzog** [comment]
Problem fixed.

**Comment by bruderol** [comment]
cool :smile: :+1: 
I tested it :smile:
