### ISSUE TITLE
Overloaded browser shortcuts Ctrl + End/Home in use case overview

### ISSUE THREAD

**Issue by mautechr** [scenarioo/scenarioo#350]
GIVEN: I am in use case overview (with Chrome)
WHEN: I press Ctrl + End 
THEN; I'm getting following message: "The step you are looking for does not exist..."

Expected: I would like to skip to the end of the use case list (as I usually do in a web browser). Same behavior with Ctrl + Home.

Hint: it seems that this strange behavior only occurred in use case overview

I would prefer to let all browser specific shortcuts as it is.

**Comment by adiherzog** [comment]
I can't reproduce this problem. If somebody can, please reopen the issue.
