### ISSUE TITLE
Introduce Base class for all classes that need access to the Browser

### ISSUE THREAD

**Issue by aax** [scenarioo/scenarioo#360]
Some classes are not PageObjects, but still need access to the Browser: e.g. Prompt, which serves as a wrapper for Selenium Alerts. 

It would be nice if classes like that didn't reference the Browser singleton directly through BrowserResource.getBrowser(), but instead through a getBrowser() method defined centrally, i.e. in a common base class.

**Comment by adiherzog** [comment]
Moved to scenarioo/scenarioo-selenium-demo#11.
