### ISSUE TITLE
Make PageComponent a self-bounded generic type

### ISSUE THREAD

**Issue by aax** [scenarioo/scenarioo#361]
It would be nice if the base class PageComponent contained a method `waitUntil(Predicate<MyComponent>)` that could be used like this in MyComponent: `waitUntil(self -> self.getTitle().equals("something"))`

For this to be possible, we need self-bounded generics:
```java
class PageComponent<T extends PageComponent<T>> {
  public void waitUntil(Predicate<T> predicate) {
    ...
  }
}

class MyComponent extends PageComponent<MyComponent> {
  public void waitForSomething() {
    waitUntil(self -> waitUntil(self -> self.getTitle().equals("something"));
  }

  private String getTitle() {
    return ...;
  }
}
```

The same mechanism could of course also be applied to other functionalities than waits.

**Comment by adiherzog** [comment]
Moved to scenarioo/scenarioo-selenium-demo#10.
