### ISSUE TITLE
UI Prototyping in Scenarioo

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#378]
This is a placeholder for all stories related somehow to prototyping or wireframing using the screens stored in Scenarioo.

We have three possible strategies identified:
 * draw like a canvas on the screenshots (idea by @danielsuter but I did not find the story ??)
 * let the user somehow manipulate the DOM elements of a screen (no separate story yet, only this here)
 * export the screen or DOM tree somehow to a 3rd party tool (balsamiq, ...) such that the user can modify it there or draw above it (see story #347).

Furthermore the following story could also be helpful to comment on prototypes or to at least link prototypes drawn in 3rd party tools as links below a screen:
 * adding comments on steps or objects, see story #180

**Comment by adiherzog** [comment]
This is currently a bachelor thesis. See: https://github.com/MyrionPhoenixmoon/scenarioo

**Comment by bruderol** [comment]
This has been realized as a first "minimum viable product" in a bachelor thesis and will be soon released in the next release 2.2 of scenarioo. Thanks to @MyrionPhoenixmoon and @parabolika66 :+1: :top: :100: 

@adiherzog is working on getting it ready to be released.

**Comment by bruderol** [comment]
one question: why does @parabolika66 not show up in the contributions list? did she allways commit with the account of @MyrionPhoenixmoons? It's a pity, she doesn't show up as a contributor, because she surely had a big impact on this feature.
