### ISSUE TITLE
Update npm and bower dependencies

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#379]
From time to time we should update to the latest npm and bower dependencies.

I already started doing this but I am not yet finished. Therefore I directly assign this to myself.

The tool https://www.npmjs.org/package/npm-check-updates is a great help for such updates.

Installation: `npm install -g npm-check-updates`

**Comment by adiherzog** [comment]
This was partially done during the Coding Days 2015. But probably we still have some old dependencies.

**Comment by xeronimus** [comment]
As of mid 2015, the trend definitely goes towards npm for fe dependencies as well. This would remove bower from the picture and simplify dep management.

In my projects it also proved  beneficial to run dep check during CI (with a small gulp task)

**Comment by danielsuter** [comment]
I upgraded most libraries or all which were possible during my angular 1.5 upgrade task. Please note, that's it's not that easy to find compatible versions. Even now we have a warning, which we can't fix because a dependency uses deprecated code of another dependency.

**Comment by bruderol** [comment]
@danielsuter Anything to do here for now, or can we close that?
@adiherzog what you think?

**Comment by danielsuter** [comment]
Imho we can close it.

**Comment by bruderol** [comment]
good for me
