### ISSUE TITLE
Correct order of branches in branch selection dropdown

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#382]
Currently the order of branches in the branch selection dropdown is not very practical and different to the build selection dropdown.

**Acceptance criterias**
 * The branch aliases should be listed first (in alphabetical order)
 * The other branches should be listed next (in alphabetic order)

**Comment by xeronimus** [comment]
@adiherzog : please review my commit

**Comment by adiherzog** [comment]
Thanks @xeronimus for your contribution. Nice implementation with the filter :-)

I added an assertion in one web test to make sure the order is correct.

**Comment by bruderol** [comment]
works fine and looks cool :smiley:  - thank you a lot! :+1: :+1:
