### ISSUE TITLE
Branch and Build Selection not working with allready selected item

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#383]
Currently it is very strange for the user, that selecting the currently selected item (both in branch and build selection dropdown) does not work. This is not nice and often confusing.

**Acceptance criterias**
 * It should be possible to select the currently selected build and also the currently selected branch in the dropdowns --> Should simply refresh the current page and close the dropdown. 
 * story #342 is also closed

** Implementation Details**
This does currently not have any effect because it does not change the URL, like all other selection items. We might have to close the dropdown programmatically somehow.

See known issue #342 (duplicate of this story), to be closed when this story is resolved.

**Comment by adiherzog** [comment]
Problem fixed.
