### ISSUE TITLE
Example with SWTBot for Eclipse RCP Applications

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#387]
Develop such an example as reusable blueprint.

**Comment by adiherzog** [comment]
This idea was brought up by @Fredericson during today's monthly meeting. He might work on this during the Coding Days. If anybody else is interested in the same topic and wants to join him, please leave a note here.

**Comment by bruderol** [comment]
I put this to working, because Fredy is making great progress with this. 

I think just some minor improvements of more prominently linking this example and we could close it.

**Comment by bruderol** [comment]
@adiherzog @Fredericson I consider this as done and will close it now.
