### ISSUE TITLE
Show available space of partition where documentation is stored

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#388]
As the administrator of a Scenarioo installation I want to see how much free space is left on the disk where the documentation data is stored so that I know when I have to start deleting old builds.

Possible follow-up story: Implement a warning mechanism (e.g. by e-mail or just in the UI) to inform the administrator when free disk space falls below a certain threshold.

Technically it seems this should be possible with Java (unless there are some security restrictions in using this function): http://stackoverflow.com/questions/1051295/how-to-find-how-much-disk-space-is-left-using-java

**Comment by bruderol** [comment]
I reconsidered priorisation and decided to close this issue - this does not necessarily have to be solved by the application but can better be solved by monitoring of the server infrastructure where scenarioo is running - not our responsibility to solve this in the application.
