### ISSUE TITLE
Test first time popup correctly in e2e tests

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#389]
Currently the first time popup is tested in the e2e tests, but we can only test it in the first web test. Therefore the webtests can not be executed in a random order. This should be improved.

Acceptance criteria:

* Control the local storage in the e2e tests so that the "first time" info popup is only shown when we really need it
* Rename a_list_use_cases.js to list_use_cases.js, because it does not have to be the first test anymore.

**Comment by adiherzog** [comment]
Use the protractor executeScript function to set / delete the local storage key.

**Comment by bruderol** [comment]
Cool :-)
