### ISSUE TITLE
Screen Annotations: Show all dropdown choices on screenshot

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#393]
As a Scenarioo user I want to see what values I can pick in a dropdown in order to get more information about the functionality of a screen.

#### Acceptance criteria

* The generator of the documentation data can also provide a list of choices for a dropdown
* The generator of the documentation can mark the region of the dropdown (similar to #149)
* The Scenarioo client then shows the dropdown region highlighted (similar to #149, maybe a different color or style, because it is not a link to a different page)
* When the dropdown area is clicked, the possible choices are shown.
* The list of choices can be closed again by the user

**Comment by bruderol** [comment]
wow, cool idea :-) :+1: 

I have an idea for a more "generic" concept, to also support different similar requirements, I think we should design this as follows:
Possibility for generic visual annotations in screens with popups for additional informations about the marked regions. The additional informations showed in this popups could be usual ObjectDescriptions (with any key value informations, or even tree structures inside, as allready provided in Scenarioo in allmost all other places). With a concept like this you can model such things (like popups with informations about all contained items) easily. And this design gives the application-test-developers a lot of power about what information they want to annotate additionally on screens.
Even more, the allready existing "object repository" could even be used to find all occurances of the same kind of ui elements (e.g. all dropdowns with countries).

**Comment by bruderol** [comment]
See story #149 about Screen Annotations:
This story should allready cover this requirements here more or less.

When story #149 is closed, we can decide whether we need to add more specific functionality to support a more comfortable version for highlighting dropdowns with selection items (maybe a more nicer styling especially for such dropdowns ?? ).

**Comment by bruderol** [comment]
I think, we can close this, because the current implementation allready enables to use to display all possible choices in the details of the popup dialog on a screen annotation. Agree?

**Comment by adiherzog** [comment]
Yes I agree, the current solution covers this more or less. It might still be an issue if the drop down contains many many values, but let's solve this when somebody actually runs into this problem.
