### ISSUE TITLE
Improve search field instructions in Use Case

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#397]
I received a feedback from a Scenarioo user who found the hint "Search scenario..." is confusing. To her it sounded like you can use this to search the entire application. Therefore we could rename it to something like: Search within Use Case "Log In"

**Comment by xeronimus** [comment]
@adiherzog , please review my commit

**Comment by adiherzog** [comment]
Thanks @xeronimus for the implementation :+1: I reviewed it and made some minor changes. Now I close the issue.

**Comment by bruderol** [comment]
Me personaly, I not like the very verbose and long texts in the search fields, but I agree that it is better undestandable than before. Thank you. :+1: 

Maybe we can improve this once to have less verbose texts that are still precise enough for good user guidance. @adiherzog what you think about this? should I open a story, or do you disagree?
(of course this is not high prio)

**Comment by adiherzog** [comment]
@bruderol I think we can leave it like this.
