### ISSUE TITLE
Improve Webpage

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#403]
Acceptance criterias
* important link to "getting started" tutorial is directly available on top of page
* Maybe instead 4 links on top: "View Demo", "Getting Started", "Downloads", "Project on Github" (or even leave the last away or make it smaller, because not important for most users)
* Download link leads to a page explaining the different download possibilities (webapp, libraries etc.)
* On all pages differentiate better between "Scenarioo Docu Viewer" (=the webapp!) and the "Scenarioo Docu Writer" (=the APIs in different technologies!)
* optional: improve design, improve screenshots (carousel, see other story!)
* optional: improve texts
* optional: add additional parts (e.g. Twitter integration, contacts, etc.) --> better plan additional stories!

**Comment by adiherzog** [comment]
@bruderol Seems this is finished, right? Can we close it?

**Comment by bruderol** [comment]
Yes this is finished. I close it.
