### ISSUE TITLE
Remove bower and always npm instead

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#409]
Why? Because its simpler to just have one dependency manager.

### Acceptance criteria

* bower is not needed anymore for Scenarioo development
* bower is removed from the build server
* npm is used instead for all dependencies
* The wiki is adapted
* All developers are informed about the change by e-mail

### Implementation

See: https://gofore.com/ohjelmistokehitys/stop-using-bower/

**Comment by adiherzog** [comment]
This is not very high priority. Therefore I set it to Prio 2.

**Comment by adiherzog** [comment]
Duplicate Issue from @danielsuter (#457):

Probably all our dependencies could be managed by NPM. We started removing it for our jass challenge and it worked well. We should check, if this is also a possibility for the scenarioo-client.

https://gofore.com/stop-using-bower/
https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb

**Comment by danielsuter** [comment]
Decision:
As it is not clear yet, what the best practises are and we do not have any pain, we decided not to implement this issue.
