### ISSUE TITLE
Fix the "go to first step" link on the scenario list page

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#411]
For some reason, a fallback page is shown whenever the "go to first step" link is clicked.

**Comment by adiherzog** [comment]
@bruderol The "go to first step" link has been broken for quite some time (even on our master branch). As nobody discovered this problem for so long, I assume that the feature is not important. Therefore I suggest to remove this link and the entire "Actions" column in the scenario list. Do you agree?

**Comment by bruderol** [comment]
@adiherzog 
1. I agree to remove it when it does not work anyway
2. I think it was a good idea, to have some possibility to directly jump into the first step, but the current icons and user interface is not understood, this needs to be solved differently.

**Comment by bruderol** [comment]
@adiherzog Where is this link?? I do not find it (even not on master).

And / but:
The shortcuts Ctrl+Home and Ctrl+End do not work --> show error page

**Comment by bruderol** [comment]
@adiherzog ... ah, I think I understand now ... on the scenario list, right ?? (I was looking on the step page)

**Comment by adiherzog** [comment]
yes, you are right, see title ;-)

**Comment by bruderol** [comment]
I found out thta there seems to be a problem only in case that the Use case has a space in its name, for other use cases the link works. Probably encoding done wrong ...

**Comment by bruderol** [comment]
This seems indeed easy to fix, there are unnecessary encodeURIComponent-calls in the controller when it defines the link. I removed this and now it works again (also for use cases with spaces in names).
