### ISSUE TITLE
E2E Tests: Add jasmine xml test reporter for Jenkins

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#413]

**Comment by bruderol** [comment]
@adiherzog Hmm, what happens currently when a test fails? Do we just get an ugly error? Or what?

**Comment by adiherzog** [comment]
I think currently the Jenkins Job Just fails and one has to check the Console Output for information about the exact problems.

**Comment by bruderol** [comment]
ah, yes, that's true. would be great if we could see the test failures properly as report inside jenkins

**Comment by bruderol** [comment]
I know about how to solve this. Did the same in my current project. Will have a look at it soon.

**Comment by bruderol** [comment]
report generation included, waiting for jenkins build to be run, to see if jenkins integration works as expected.

**Comment by bruderol** [comment]
done
