### ISSUE TITLE
Store client side user data per scenarioo instance

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#416]
As a user I want Scenarioo to remember any values in local storage on client side in such a way that this values are remembered separately for multiple instances of scenarioo, such that I can browse between multiple instances of scenarioo running on the same server without having the trouble to allways have to select the branch and build on each instance.

Acceptance criteria
 * When I select a build or branch in scenarioo demo for Master branch and I switch then to the scenarioo demo for develop branch, Scenarioo will still select the branch and build, that was selected there the last time (or the default = "wikipedia-example" with "Last successful").
 * also all other values that are remembered in local storage should be saved with a key tha depends on the scenarioo instance name.

**Comment by bruderol** [comment]
It is really annoying for the demo when switching between branches.

**Comment by adiherzog** [comment]
I agree. I just added the important label.

For the technical solution every Scenarioo instance needs a technical key that we can use as a prefix for all local storage keys. This could maybe be the servlet context that we could extract from the URL.

**Comment by bruderol** [comment]
Of course it should be the path to the scenarioo instance taken from the URL

**Comment by bruderol** [comment]
I started to implement this for release 2.2

**Comment by bruderol** [comment]
There is a problem with current implementation, I know about it. I try to fix it this afternoon.

**Comment by bruderol** [comment]
Problems should be fixed, e2e tests should be stable again, will test it now extensively to be sure, it is safe.

**Comment by bruderol** [comment]
e2e tests are stable, but:
1. context path parsed from url used in storage seems to be still wrong
2. some code duplications needs to be resolved
3. the logic (which is wrong) needs a unit test

I try to improve this 3 points.

**Comment by bruderol** [comment]
improved and cleaned up code for local storage context path calculation:
- extracted service and unit tested it for correct context path from url calculation
- cleaned up and fixed context path calculation code
- reuse scLocalStorage service from injector also in e2e tests (for initializing the stroage)
- some final manual testing :ok: 

I consider this done, and close it.

**Comment by adiherzog** [comment]
I just did a quick test and it seems to work fine. Great that you managed to reuse the logic in the e2e tests as well! :+1:
