### ISSUE TITLE
Use John Papa Style in all our controllers

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#417]
See: https://github.com/scenarioo/scenarioo/wiki/Coding-guidelines

Many controllers were already changed to this style, but some are still left (e.g. step.js).

**Comment by bruderol** [comment]
moved it to the client cleanup milestone that needs cleanup anyway - not sure what we do with that. 

Probably we can close, since this will be addresed in angular/typescript migration anyway?

**Comment by adiherzog** [comment]
@bruderol Yes, I'll close it.
