### ISSUE TITLE
Bug: Wrong Step Numbers in Scenario Overview

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#419]
Step numbers in scenario overview are wrong (not increasing):

![scenarioo_wrong_step_numbering](https://cloud.githubusercontent.com/assets/755721/8693188/8c82e5f6-2ad5-11e5-97fb-759209e30610.png)

this is even broken on master branch.

In earlier versions this looked different:
![scenarioo_step_numbering_earlier_versions](https://cloud.githubusercontent.com/assets/755721/8693310/830e584c-2ad6-11e5-9995-4a02a7a2c5f4.png)

This was also suboptimal before, because the number behind the text "Step" seems to be the page number and not realy the step number. Also I do not know how this looked for substeps in a page.

Also the text "Step 1 of x" is missing, such that we see how many steps are there for one page.

**I propose the following:**
* Behind the page title we show in brackets the number of steps: "Page: search.jsp (3 Steps)"
* The Title of the steps is simply "1.1 - Title 1", "2.1 - Title 2" where the first number is the page number and the second number the step number on this page

**Comment by adiherzog** [comment]
I think it's not actually a bug. We probably once decided to do it like it is now. The step numbers within one page are actually increasing.

But I'm open to change it again, If you think it's too confusing now.

**Comment by bruderol** [comment]
yes, this is confusing.

**Comment by bruderol** [comment]
Ok I think about this again, both versions seem not optimal to me.

What do you think about this new proposed solution:
* Display "Page 1: " for "Page:" 
* Display the number of stpes behind the page title "(3 Steps)"
* Then I agree, that we can keep "Step 1:" because the number of steps in one page and at least the page index is visible and increasing. 

@adiherzog ? What do you think?

But yes, it is not a bug. I agree. This will not block the release.
I keep it here in the releas milestone, will have a look at it, if I can fix it in some minutes, I do, otherwise I will put it to prio1.

**Comment by adiherzog** [comment]
Let's just put it to prio 1 and then think about a solution that we will still be happy with after another year.

**Comment by bruderol** [comment]
I agree that we can make this better in the next release, but since this was easy, I at least added folowing information:
 * index of page in page title (same as for step): "Page 1: bla.jsp"
 * number of steps on one page behind page title "(3 steps)
