### ISSUE TITLE
Add new builds by POST request

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#424]
As a developer I want to easily add new builds to a Scenarioo installation, even if I do not have file system access to the installation.

Requested by @xeronimus and @tobiaszuercher.

## Acceptance criteria

* New builds can be added using a POST request to a certain Scenarioo URL
* New builds can only be added by authenticated users with a certain role

## Tasks

Done:

* Create feature branch
* Add new REST endpoint
* Make REST endpoint accept a zipped Scenarioo build and extract it into the correct folder
* Do not overwrite branch.xml, if it already exists
* Use BASIC authentication (not an API key in the GET parameters)
* Handle errors better
* Handle special cases (e.g. the case where the same build folder already exists)
* Document feature in Wiki

**Comment by adiherzog** [comment]
Started the implementation and proved that it works. Now I still need to do more testing, better exception handling and improve the security of the API key.

Also documented the usage here: https://github.com/scenarioo/scenarioo/wiki/Publish-Documentation-Data

@xeronimus @tobiaszuercher @bruderol Feedback is welcome, please have a look at the specification of this issue and the documentaiton in the wiki. It's not too late for some changes.

**Comment by adiherzog** [comment]
@tobiaszuercher I changed the design to use BASIC authentication. This means a user has to be configured in `tomcat-users.xml`. The documentation is updated accordingly. The implementation will follow soon. https://github.com/scenarioo/scenarioo/wiki/Publish-Documentation-Data

**Comment by adiherzog** [comment]
@tobiaszuercher @xeronimus @bruderol I'm done implementing this. Could you please have a look whether that's what you wanted? The documentation can be found here: https://github.com/scenarioo/scenarioo/wiki/Publish-Documentation-Data

If I don't hear from you until tomorrow evening I will merge into the develop branch next week.

**Comment by bruderol** [comment]
Cool stuff! :+1: :smile: 
Just one thing: The role name "scenarioo-post-build" is confusing (has it something to do with the technology of Post-Requests? why is there a technology-specific thing in a role name? Is it only for post-build-actions?) ... I think a better name would be something like "scenarioo-content-publisher". Later we could add additional roles like "scenarioo-administrator" (by the way: would be a good idea to protect the configuration page accordingly, later)

**Comment by bruderol** [comment]
Cool stuff! :+1: :smile: 

Just two things:
1. The role name "scenarioo-post-build" is somehow confusing (has it something to do with the technology of Post-Requests? why is there such a technology-specific thing in a role name? Or is it only for post-build-actions?) ... I think a better name would be something like "scenarioo-content-publisher". Later we could add additional roles like "scenarioo-administrator" (by the way: it would be a good idea to protect the configuration page accordingly, later ... is this the first step into a scenarioo user/authorization concept?)
2. One idea for improvement (maybe open a new story for later ...): For just adding a build to an allready existing branch, it would be great if the branch was just an URL parameter and no branch-directory & -file was necessary in the ZIP. this would make the service even more easy to use.

**Comment by bruderol** [comment]
Habe die neue WIKI Seite minim ergänzt: ich habe noch erwähnt dass auch direkt in das Scenarioo-Doku-Verzeichnis generiert werden kann, wobei das build.xml jeweils erst geschrieben werden soll, wenn der ganze Build fertig generiert ist, um zu frühes importieren zu verhindern.

**Comment by adiherzog** [comment]
Thanks @bruderol for your input. I will rename the role, probably to `scenarioo-build-publisher`.

I think the second idea is not so important. It might help slightly when adding builds manually, but as soon as the process is automated, it has to handle both cases (the one with and the one without an existing branch).

@tobiaszuercher I will try to finish this story tomorrow morning. If you have any feedback, please let me know as soon as possible.

**Comment by adiherzog** [comment]
Merged into the develop branch and tested it again. There is not automatic regression test for this feature.
