### ISSUE TITLE
Automatically install chrome webdriver if not present

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#428]
The gulp build tasks `test-e2e` and `test-e2e-scenarioo` should automatically check whether the following line needs to be executed. If yes, it should automatically be executed.

```
./node_modules/gulp-protractor/node_modules/protractor/bin/webdriver-manager update --chrome
```

**Comment by bruderol** [comment]
Not sure, how we could check that. Is there a way to find out, whether the currently installed web driver matches the local chrome version? Or would it just be okay to update allways? Normally this should work.

**Comment by adiherzog** [comment]
I added the call to the webdriver-manager as a `postinstall` hook in the package.json file. This way it is executed every time `npm install` is executed. See commit https://github.com/scenarioo/scenarioo/commit/4119b0378cc6a3bffe7a814a245bd48975215c00

@bruderol Do you think that's a good solution? I read somewhere that you had issues with this on Windows.

**Comment by bruderol** [comment]
Yes, the path that you commited does not work on my machine. But maybe we can have a look at this together.

Also I am not sure, if that is what we want. The driver has to be in sync with the chrome browser, how does this ensure it? Not really. Why not let the developer decide when he has to update it? It should just go into our cheat sheet for developers, such that they know that they need update the webdriver sometimes.

**Comment by bruderol** [comment]
I put this to in progress, because you allready started a solution that is probably not optimal. Important that we find a solution that works stable for everybody and also for the CI.

**Comment by adiherzog** [comment]
I removed the line from `package.json` again, so i put this issue back to "ready".

**Comment by bruderol** [comment]
Not sure if we realy need this. 

For Devs: document it, that they have to call it form time to time
For CI: maybe a build job that updates chrome and webriver together?

**Comment by danielsuter** [comment]
I find the post install hook pretty useful. The dev cannot choose a specific version anyways.

**Comment by bruderol** [comment]
me not, because it was not working on windows dev env with intellij !!
It is the devs repsonisbility to update when needed, that is realy easy.

**Comment by adiherzog** [comment]
On the CI the webdriver-manager is currently updated in the e2e test build (see e.g. http://54.88.202.24/jenkins/job/deploy-demo-and-run-e2e-tests/723/console). I guess that's ok for now. In case webdriver becomes suddenly incompatible with our chrome version we just have to go and update chrome.

**Comment by bruderol** [comment]
Can we then close this for now?
