### ISSUE TITLE
John Papa: Organize files by page or functionality, not by type

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#429]
Currently our files are organized by file type (e.g. all controllers in one place, all HTML files in a different place). We should change this and organize files by page or functionality. Furthermore the following rules of the John Papa Style Guide must be implemented.

### Folders-by-Feature Structure

Create folders named for the feature they represent. When a folder grows to contain more than 7 files, start to consider creating a folder for them. Your threshold may be different, so adjust as needed.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y152

#### New structure

As defined by @mi-we @danielsuter @adiherzog on 2016-05-09.

* build
* useCase
* scenario
* step
  * screenAnnotations
* sketcher
* objectRepository
* manage
  * buildImport
  * generalSettings
  * branchAliases
  * labelColors
* shared
  * navigation (inkl. Info Popup)
  * metadata
  * filterableTableTree
  * sharePage

### Naming Guidelines

Use consistent names for all components following a pattern that describes the component's feature then its type: `feature.type.js`.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y120

### Test File Names

Name test specifications similar to the component they test with a suffix of `spec`.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y122

### Controller Names

Use consistent names for all controllers named after their feature. Use UpperCamelCase for controllers, as they are constructors.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y123

### Controller Name Suffix

Append the controller name with the suffix `Controller`.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y124

### Factory and Service Names

Use consistent names for all factories and services named after their feature. Use camel-casing for services and factories. Avoid prefixing factories and services with $. Suffix service and factories with Service.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y125

### Directive Component Names

Use consistent names for all directives using camel-case. Use a short prefix to describe the area that the directives belong (some example are company prefix or project prefix). For Scenarioo we use the prefix `sc`.

https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y126

**Comment by bruderol** [comment]
a candidate for the minicamp. I put it to next release to be considered. We have to take care to not disturb the current work of "Diff Viewer" bachelor thesis too much.

**Comment by adiherzog** [comment]
I think moving files around will not be the biggest problem for the "Diff Viewer" project as git can handle that quite well. The biggest problem will be changing everything in the JS files to John Papa style which will hardly leave a line untouched (except for the files that are already conforming to the style guide) ...

@danielsuter @bruderol Please agree regarding a strategy for the students to deal with that problem. I currently see these two solutions:

a) The students work on their fork without merging our changes. In the end we do kind of a manual merge of their features into our develop branch. This would be quite a big one time effort, but has the big benefit that the students do not have to care about our changes and can fully concentrate on delivering a good solution for the "Diff Viewer" project.

b) The students regularly integrate our changes from develop into their fork, which eats up some of their time that they could spend creating the "Diff Viewer". Here we should probably give them assistance or even do some of the merging by ourselves after bigger changes (especially during the mini camp).

I think it's important to make a clear decision and stick to it. What do you think?

**Comment by bruderol** [comment]
yes, I agree.

But we can decide this spontaneous in accordance with them depending on the changes.

I do not see a big issue for now, we just have to keep this in mind

**Comment by danielsuter** [comment]
We agreed on version b to make sure their work will be made available to everybody soon after it's finished.

**Comment by bruderol** [comment]
@danielsuter @adiherzog 
Great work guys! Could you give a short introduction to the new structure on the next scenarioo monthly please??
