### ISSUE TITLE
Bug: Page variant browsing link is broken

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#432]
feature #247 seems not to work anymore, as expected (on develop branch).

**Comment by adiherzog** [comment]
@bruderol I think this still works, just tested it. Could you please check again?

**Comment by bruderol** [comment]
For me it does not work (clicking the page-variants link has no effect)

Tested In Firefox on following page:
http://54.88.202.24/scenarioo-develop/#/step/Find%20Page/find_multiple_results/searchResults.jsp/0/0?branch=wikipedia-docu-example&build=last%20successful

**Comment by bruderol** [comment]
In Chrome it works.
In IE same as Firefox (not work).

It is not just the link that does not work:
also the mouse-over-tooltip-popups on the navigation buttons are not working in Firefox and IE.

**Comment by xeronimus** [comment]
yep. the problem is that you nested a anchor tag (<a href="url to page variant">Page Variant 2 of 24</a>)  inside a button tag.

**Comment by adiherzog** [comment]
Thanks @xeronimus. I just tested it and merged it into the release-2.1 branch.

**Comment by bruderol** [comment]
perfect. Thank you so much!

**Comment by bruderol** [comment]
but the same problem still exists with all other navigation buttons: popup tooltips not working anymore.
@adiherzog you changed this once to buttons and since then all the tooltips not work anymore.

I will open a new issue.
