### ISSUE TITLE
Bug: Scenarioo Deployment with different WAR-file-name seems not to work somehow?

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#433]
Reported by @dpfulg:
 
Using WAR file with a different name than "scenarioo.war" seems to cause problems.

Steps to reproduce:
* Downloaded scenarioo2.0.1.war File into the webapps folder of tomcat (or other server?)
* do the configuration (I have no clue what he means? Probably setting the documentation path on the configuration page?)
* execute "Import & Update Builds"
* unexpected result: the branches and builds are not found

Workaround:
* after renaming the WAR file to "scenarioo.war" everything worked as expected

Question by the reporter:
Is there a hardcoded path inside somewhere or why can this happen?

**Comment by bruderol** [comment]
@adiherzog could this be the same issue that you had when testing the sketcher relase in your project?

**Comment by bruderol** [comment]
I asked the reporter following questions:
1. Was there allready a different scenarioo version installed on the same server before?
2. under which URL do you access the webapp?

**Comment by tobiaszuercher** [comment]
it was a fresh installation of tomcat 8, we also tried it with 7.

i want to add that in the manage grid (/manage) there was no import listed but clicking to home actually showed use cases & scenarios.

**Comment by adiherzog** [comment]
As this is the "old" version 2.0.1 and not the develop branch, it's not the same problem that I had with the develop branch. I definitely already deployed Scenarioo with names other than scenarioo.war, but never with a version number in the war file name. I will try to do this on my machine tomorrow.

**Comment by tobiaszuercher** [comment]
@bruderol to properly answer your questions:

1. nope, vanilla tomcat
2. http://localhost:8080/scenarioo2.0.1

**Comment by dpfulg** [comment]
I will try to reproduce the problem by renaming the webapp back to scenarioo2.0.1

**Comment by adiherzog** [comment]
I contacted @dpfulg and will help him solve the problem.

**Comment by tobiaszuercher** [comment]
it was probably just a IE thing :/

**Comment by bruderol** [comment]
Could it be, that it was a caching problem?
We still should setup our HTTP caching headers for the REST services appropriately ...
see #34 and #276

**Comment by adiherzog** [comment]
Just talked to @dpfulg about it. After some trying the problem disappeared. It was probably IE 11 specific. I told him to open issues if he finds reproducible problems with IE or in general. We decided to close this issue.
