### ISSUE TITLE
scenarioo-java 2.0.1 in mvn-repo not available

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#435]
The current version of scenarioo is not available in mvn-repo, as described here:
https://github.com/scenarioo/scenarioo-java/wiki/How-to-use-the-Java-Scenarioo-Writer-Library#getting-the-java-library-as-a-jar

Somehow only a SNAPSHOT is in the Repo.

**Comment by bruderol** [comment]
It seems as if we forgot the last time to make a proper release in mvn-repo :-1: 
(maybe my fault?)

**Comment by adiherzog** [comment]
There is no 2.0.1 release of the API yet. The Writer 2.0.1 uses the API 2.0.0.

**Comment by bruderol** [comment]
aha, okay, you are right ... but then the documentation is wrong!

**Comment by bruderol** [comment]
I updated the following WIKI page accordingly:
https://github.com/scenarioo/scenarioo-java/wiki/How-to-use-the-Java-Scenarioo-Writer-Library#getting-the-java-library-as-a-jar

I also linked to @danielsuter 's Tutorial and new example on this wiki page.

**Comment by adiherzog** [comment]
Thanks for the improvements!
