### ISSUE TITLE
HTML View is broken in 2.1.0

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo#446]
HTML code won't be shown in version 2.1.0. This was most probably broken with the screen annotation release. The step.xml files contain the html code but it won't be displayed in the scenarioo viewer web application.

You can reproduce this issue in the scenarioo demo version.
1. http://54.88.202.24/scenarioo-master/#/step/Donate/find_donate_page/searchResults.jsp/0/0?branch=wikipedia-docu-example&build=last%20successful
2. Open HTML tab

**Comment by bruderol** [comment]
I put this to academy and ready to code, because urgent. Would be great if somebody could fix this together with #454

**Comment by bruderol** [comment]
@mi-we I will remove this branch. Please take care to remove remote branches when merged to develop. Thanks
