### ISSUE TITLE
Page numbers are wrong in version 2.1

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#447]
Page number is always 1, which is wrong. Instead, pages should be numbered 1, 2, 3, etc.

![page numbers wrong](https://cloud.githubusercontent.com/assets/3780183/11941692/bde1f518-a831-11e5-8126-e46f7853b957.PNG)

**Comment by bruderol** [comment]
@mi-we Thanks for the fix! Great solution!
