### ISSUE TITLE
Scenarioo Format Validation Tool

### ISSUE THREAD

**Issue by xeronimus** [scenarioo/scenarioo#451]
Developers that implement various writer APIs (C#, JS) need a tool to validate their scenarioo docu output (folder structure + xml files).

### Acceptance Criteria
* Implement a command line tool (java class with main method)  that validates a given directory containing scenarioo docu outpu.
* Use Build Import functionality from the scenarioo server
* The tool should validate folder structure
* The tool should validate xml schema validity
* The tool should validate successful aggregation

**Comment by xeronimus** [comment]
Merged into develop. Currently I'm working on documentation in the wiki.
should I add a one-liner README file to the scenarioo-validator directory as well?

**Comment by xeronimus** [comment]
If we add the gradle build step of the validator tool to our CI, we could link to the produced zip file somewhere.
This would allow developers to use the tool without cloning the repo and building it themselves.

what do you think?

**Comment by bruderol** [comment]
yes, great, :+1: from my side

**Comment by xeronimus** [comment]
Since I cannot modify the jenkins build. this would be up to you :)

add another gradle task `gradle build distZip`  to the build job. This will bundle the validator and place the zip here:  scenarioo/scenarioo-validator/build/distributions/scenarioo-validator-latest.zip

**Comment by adiherzog** [comment]
Good stuff :-) I added it to the build of the develop and the master branch and you can find the artifact here: http://54.88.202.24/jenkins/job/scenarioo-develop/lastSuccessfulBuild/artifact/scenarioo-validator/build/distributions/ (for develop). Is that ok?

**Comment by xeronimus** [comment]
That's great, thanks. I'm gonna put the link into the wiki... ☺

Adrian Herzog <notifications@github.com> schrieb am Sa., 6. Feb. 2016 23:27:

**Comment by bruderol** [comment]
@xeronimus Can we close that? Or is there something open?

**Comment by xeronimus** [comment]
I updated the wiki.
