### ISSUE TITLE
Improve npm scripts

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo#456]
At the moment we need to know that we're using gulp and bower and start the tasks manually.

As a developer I want to type npm install and expect that all dependencies will be downloaded (including bower).
As a developer I want to type npm test and all tests should be executed, so I can savely commit.
As a developer I want to type npm start to get the scenarioo frontend running.

**Comment by bruderol** [comment]
:+1: yes! :smile:

**Comment by bruderol** [comment]
Did you document this in the developer guidelines in the wiki ???

**Comment by danielsuter** [comment]
Yes.
