### ISSUE TITLE
Upgrade to latest angular version

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo#458]

**Comment by adiherzog** [comment]
The latest version would be 1.5.0 ennoblement-facilitation (2016-02-05).

Does anyobody have time to look into this? Would be great if we could achieve this before the Camp in Mai and the sooner we do it, the better for the students who work on the "Diff Viewer".

**Comment by danielsuter** [comment]
I'm looking into this so that the students may work with the latest angular version.
At the moment I'm fighting with angular-ui. I had to do a major upgrade there (from 0.1x to 1.x). They changed all element and service names. Lazy preloading is not working at the moment.

**Comment by danielsuter** [comment]
Drop down is also not working. This is likely an angular upgrade issue.

**Comment by bruderol** [comment]
At least @danielsuter and me could fix the tabs with lazy loading today in a short pair programming session. Thank you @danielsuter :+1:

**Comment by bruderol** [comment]
@danielsuter 
Can you please wait with merging this to develop until we finished release 2.2

**Comment by adiherzog** [comment]
@bruderol I would actually also include this into the next release... Why do you think we should wait with this? I don't like the idea of having a number of feature branches waiting for later integration.

**Comment by bruderol** [comment]
@adiherzog 
And I do not like to integrate risky changes short before releasing a new release. Especially not, if those changes (like the angular 1.5 update) do not really add any direct value to the user.

Let's make this release happen soon and fast, and let's make it a well tested stable release and then we can integrate risky things right after the release and have time again to test this good enough.

If you not agree, please contact me personally to discuss this.

**Comment by danielsuter** [comment]
@adiherzog @bruderol 
The merge is finished. We need to upgrade the node version on our CI for the ui tests to work.

**Comment by danielsuter** [comment]
Tests seem to be working. Fixed two bugs.

**Comment by bruderol** [comment]
@danielsuter Cool, thank you so much for your effort! :+1:

**Comment by bruderol** [comment]
@danielsuter I have to reopen, because there is a branch that seems not be properly merged to develop branch: https://github.com/scenarioo/scenarioo/tree/458-upgradeAngular

Can you take care of this?

And please remove the remote branch, when done.

**Comment by danielsuter** [comment]
I have already merged this branch. I will simply delete it.
