### ISSUE TITLE
More label colors

### ISSUE THREAD

**Issue by patrickschweizer** [scenarioo/scenarioo#459]
Increase the number of selectable label colors. Colors help to get an overview quickly. 
Option: allow definition of own colors 

Solution accepted by @bruderol, @mi-we, @adiherzog:
- Simply add a text field behind the date picker, where the selected color value can be changed in more details by changing the value in format "#0099ff" (for advanced users for those rare situations, where you need another color).
- Only highlight currently selected color in the picker, if it is available in the picker
- There should be also a preview of an example of the label in currently selected style (color and name).

**Comment by bruderol** [comment]
I think there should be simply the possibility, to just change the css color "#0011ff" in a text field (without support by the picker), for more advanced users, to define labels with different colors.

But: I not consider this as a high prio feature.

**Comment by bruderol** [comment]
@patrickschweizer I proposed a solution that could be implemented (if somebody finds time), see in the story description above. Do you agree? But as I said, this is not prioritized very highy (only "prio 2").

**Comment by bruderol** [comment]
I think that would be a cool story to implement, for those who like to implement something small and easy, in Angular JS for education.

@mi-we @Fredericson @dola What you think? Somebody wants to do it as an exercise?

**Comment by mi-we** [comment]
@bruderol Yeah, would be something cool to implement. I assume that your propsed solution is ok so I'm moving this issue to Ready now.

**Comment by bruderol** [comment]
yes, very good :+1:

**Comment by bruderol** [comment]
I want exactly the same color picker as for gthub labels config UI, see here:
https://github.com/scenarioo/scenarioo-js/labels
