### ISSUE TITLE
Bug: Problem on Import without build state set

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#461]
We once implemented the feature, that the build state (and as well the use case states) are calculated from use cases and scenarios states on import of a build, but only if not set yet.

According to @abeggchr if build state (and use case states) are not set, it throws an exception as following on import: 

             > java.lang.NullPointerException
             >                at org.scenarioo.business.builds.AvailableBuildsList.updateAliasesForRecentBuilds(AvailableBuildsList.java:240)
             >                at org.scenarioo.business.builds.AvailableBuildsList.addImportedBuild(AvailableBuildsList.java:175)
             >                at org.scenarioo.business.builds.BuildImporter.addSuccessfullyImportedBuild(BuildImporter.java:218)
             >                at org.scenarioo.business.builds.BuildImporter.importBuild(BuildImporter.java:193)
             >                at org.scenarioo.business.builds.BuildImporter.access$000(BuildImporter.java:46)
             >                at org.scenarioo.business.builds.BuildImporter$1.run(BuildImporter.java:165)
             >                at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
             >                at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
             >                at java.lang.Thread.run(Unknown Source)

**Comment by bruderol** [comment]
There was a even more serious unexpected behaviour in this project (probably connected to this bug described above):
New builds weren't imported anymore and stayed in status "UNPROCESSED" when clicking on "Refresh & Import". Probably the import somehow crashed because of some build in very bad state. Not sure about that. 

We should try to fix this for the next release, as follows:
1. A build throwing an exception on import should not block other unprocessed builds from beeing imported.
2. Builds without states should be imported and the states are calculated appropriately.

Unfortunately this project is using 2.0.1 version of scenarioo viewer, so the stack trace might be outdated. They want to wait on our next release to fix this problem as well as some other bugs that we have allready fixed from version 2.1.

@mi-we @adiherzog 
This is high prio and we should try to fix this for our next release and plan a next release 2.2 very soon.

**Comment by adiherzog** [comment]
I assigned this to the milestone of the next release.

**Comment by bruderol** [comment]
@mi-we and me analysed this problem together this morning:
1. The NullPointer exception with missing build states has been fixed in version 2.1
2. We can not reproduce currently the problem with not processing unprocessed builds (might be also fixed in 2.1 or 2.2, but we do not know what might cause this problem).

@abeggchr
I will close this issue, and we recommend you to now install the current release candidate for 2.2 and test this one in your project (I sent you the link by email). We are not fixing bugs in version 2.0.1 anymore. If you still encounter problems with unprocessed builds with the new version, please let us know. Thank you very much!
