### ISSUE TITLE
Introduce Metadata-Panel for Issue Sketcher Views

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#466]
As a user of scenarioo I would expect that also in the view of a Sketch (Issue Sketcher), I can see the metadata information on the right hand side and can toggle it with "Metadata Hide|Show", such that I have the same user experience everywhere in Scenarioo and can view the metadata together with the sketch.

In the Sketcher view, the "Metadata" is displayed in its own tab. On all other pages of scenarioo we have our right hand side metadata panel, that can be toggled. I think we should use this same pattern also for issue sketcher views, such that our UI is more consistent. This should be implemented by reusing our usual component for metadata panel.

Some minor remarks about the UI of the issue sketcher (can also be extracted to other issues, if not realised on this issue):
* We should put the title of the sketch above the tabs, similar to on other pages, e.g. usecase view and instead not display it in the tab (the tab would be just "Sketch").
* the name / title of the sketch should also be displayed in the breadcrumbs ("Home / Sketches / Also Automated ..."), and when clicking on "Sketches" in the breadcrumbs, I get back to the Sketches tab.

**Comment by bruderol** [comment]
@adiherzog I put it to Release 2.2, but of course this is not mandatory for the release. It is just a important point to consider, to make the UI more consistent, that can also be realized later. Maybe it could also be something that could be solved as academy task.

**Comment by bruderol** [comment]
In case somebody wants to realize this, please talk to @adiherzog please to discuss whether this should go to release 2.2 branch or just on develop branch.

**Comment by adiherzog** [comment]
I remove this from the release 2.2 as I don't have time to implement this before the release. If somebody else wants to, of course, just go ahead.

**Comment by bruderol** [comment]
I put it to next release because we should also make such things more consistent in next release.

**Comment by bruderol** [comment]
I try out how much effort that is.

**Comment by bruderol** [comment]
seems to be very easy. I prepared it on a feature branch and I will open a pull request for the release.

what I changed:
* title for the sketch (same style as on other pages)
* metadata in usual hideable metadata panel on right side (with two collapsable sections)
* image has same style as our scenario step images on the step view (which causes it to auto scale --> more responsive)

@adiherzog if you agree I would like to see that in the release.

**Comment by bruderol** [comment]
![image](https://cloud.githubusercontent.com/assets/755721/14658724/67211d58-0696-11e6-927c-cad9555b1452.png)

**Comment by bruderol** [comment]
see PR #494

**Comment by bruderol** [comment]
in the screenshot the nice border is missing, with the last commit there is a border which makes it look even nicer - good night!

**Comment by adiherzog** [comment]
@bruderol Looks very nice in the screenshot. Please merge it as soon as possible so that you could still react in case of problems.

One thing that should be changed: Don't mention the word "Issue" in the title, as we removed this everywhere else in the UI as well. For the user only "sketches" exist. So the title should be: `Sketch "Rolfs final release test sketch"`

**Comment by bruderol** [comment]
@adiherzog ok, I changed the title and merged now. there is one other small PR open that you should look at and please merge for the release - thank you - I think that will be it then. and we are ready for the release :+1: :smile:

**Comment by adiherzog** [comment]
@bruderol Just tested it, looks good. Thanks for the change.
