### ISSUE TITLE
Dev Env: Upgrade and clean up gradle build

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo#467]
I looked at our gradle file and it looks like a mess. Why do we configure subprojects in the root gradle file? Also I could not use the latest gradle version, because the build will fail.
My suggestions:
- Define plugins where they are required (node and grunt plugin). Btw. we are not using grunt anymore.
- Recheck why resolution strategy is used
- Configure subprojects individually instead of in the root projects
- Updated to latest gradle version
- remove war plugin from client
- don't use a copy to rename the war archive but provided configuration possibilities
- don't redefine java source version everywhere

**Comment by bruderol** [comment]
agree :+1: go for it!

**Comment by bruderol** [comment]
By the way, shouldnt we upgrade to Java 1.8 ??

**Comment by danielsuter** [comment]
@bruderol 
All scenarioo users would need to run on java 8. If this is the case we should upgrade.

**Comment by danielsuter** [comment]
Imho this task is finished. I kept the copy task, since we use identical sources and this is probably the fastest way to do it.
