### ISSUE TITLE
Get build server to work after upgrading AngularJS

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#468]
The build currently does not work on the build server. I already updated node / npm / bower and chrome but there's still an issue. I will try to solve this in the next few days.

**Comment by adiherzog** [comment]
Currently the problem on the build server is the following error when executing gradle:

```
23:37:59.973 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.io.IOException: Cannot run program "bower" (in directory "/var/lib/jenkins/jobs/scenarioo-develop/workspace/scenarioo-client"): error=2, No such file or directory
23:37:59.975 [ERROR] [org.gradle.BuildExceptionReporter]        at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:69)
23:37:59.976 [ERROR] [org.gradle.BuildExceptionReporter]        ... 1 more
23:37:59.986 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.io.IOException: error=2, No such file or directory
23:37:59.987 [ERROR] [org.gradle.BuildExceptionReporter]        ... 2 more
23:37:59.987 [ERROR] [org.gradle.BuildExceptionReporter]
```

Bower is available though when being called on the command line in the scenarioo-client folder. It seems like Gradle can't access everything in the $PATH like the bash can...

Either we get this to work or we just implement #409 to get rid of bower entirely.

@bruderol @danielsuter This is just to keep you up to date with the state of the build server. I hope to get it up and running beginning of the week.

**Comment by bruderol** [comment]
Thank you a lot! Very good that you keep us updated like this! And thank you for your effort!
:+1:

**Comment by adiherzog** [comment]
Now that I got bower to work I have the problem that the built *.war file does not contain the angular client. The root of this problem seems to be that the dist folder is not created and filled in during the build. I don't understand yet why this happens as we did not change the gulpfile and the gradle scripts. Have to take a closer look into this.

**Comment by adiherzog** [comment]
Finally I could solve the issue with this tiny commit: https://github.com/scenarioo/scenarioo/commit/1a727b2dfad7fa2dd92819de7908d2aca3802011

**Comment by bruderol** [comment]
One question:
does the build (CI) still work for old version branches, e.g. for release and master branch which will be for sometimes still old angular version ??

**Comment by adiherzog** [comment]
That's a good point. I will make sure it works when I prepare the release of version 2.2.
