### ISSUE TITLE
Bug: Info popup is broken

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#469]
After the angular update the info popup does not look right: http://54.88.202.24/scenarioo-develop/#/step/Application%20startup/First%20visit/scenarioo-develop_/0/1?branch=scenarioo-self-docu&build=last%20successful

Seems that the tabs are broken.

@danielsuter Do you have time to have a look at this?

**Comment by bruderol** [comment]
related to #458

**Comment by danielsuter** [comment]
@adiherzog 
Thanks I'm looking into this.

**Comment by adiherzog** [comment]
@danielsuter Thanks for fixing it!
