### ISSUE TITLE
Build Failure in assertScreenAnnotationPopupIsDisplayed()

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#473]
http://54.88.202.24/jenkins/job/deploy-demo-and-run-e2e-tests/704/
and 
http://54.88.202.24/jenkins/job/deploy-demo-and-run-e2e-tests/705
(both the same!)

Failures:
1) View screen annotations Popup
  Message:
[31m    Expected false to be true.[0m
  Stack:
    Error: Failed expectation
        at StepPage.assertScreenAnnotationPopupIsDisplayed (/var/lib/jenkins/jobs/scenarioo-develop/workspace/scenarioo-client/test/protractorE2E/webPages/stepPage.js:187:33)
        at /var/lib/jenkins/jobs/scenarioo-develop/workspace/scenarioo-client/test/protractorE2E/specs/screen_annotations.js:58:18
        at Object.<anonymous> (/var/lib/jenkins/jobs/scenarioo-develop/workspace/scenarioo-client/test/protractorE2E/dsl/customExtendedDsl.js:30:16)

I had a look at the file  stepPage.js and on the line of error (right before) there is a strange explicit wait. I think that is not how we should write stable web tests in protractor.

@adiherzog Can we discuss it once together?

If you like we can meet next Thursday and I help you stabilize some things together (also for the Release).

**Comment by bruderol** [comment]
@adiherzog:
Ich habe auf dem Buildsystem die Builds markiert und komentiert.

Ausserdem habe ich noch das Ansi Colors Plugin auf dem Jenkins installiert und konfiguriert, das lohnt sich bei Protractor Tests damit die Protractor Ausgaben mit Ansi-Colors im Log-File auch richtig lesbar sind (sonst sieht man komische Steuerzeichen).

**Comment by adiherzog** [comment]
@bruderol I removed the wait in assertScreenAnnotationPopupIsDisplayed and also tried a few other things but nothing helped. The test always runs locally but never on the server. Therefore I commented out the problematic four lines of the test on the release branch.

As I can't invest more time into this let's just keep this issue as a "technical dept" reminder to fix this some day.

I also merged this to develop. Both builds are now successful on the CI.

**Comment by bruderol** [comment]
@adiherzog Could it be, that this issue has to do with animations. In my project we had similar issues with animations of opening popups. I turned off animations for e2e tests in issue #496. Maybe this solves this issue? Maybe we find some time to shortly look at it on the coding days?

**Comment by adiherzog** [comment]
Seems it was actually related to the animations. After activating the code again the tests ran successfully on the build server. Thanks for the hint.

**Comment by bruderol** [comment]
:+1: glad that my animation tweak solved this issue :smile:
