### ISSUE TITLE
E2E Tests: Set fixed window size for e2e tests

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#474]
Current setup in protractor onPepare sets the window to maximized which is a different resolution on different systems. this can lead to unstable tests (we had that problem in our project)

We have to set a fixed window size for e2e tests.

**Comment by adiherzog** [comment]
I think that's currently not an issue. But if it becomes one, we can fix it.

**Comment by bruderol** [comment]
Sorry, but if I know that there is a potential problem that developers will very likely run into, that I can prevent from happening with changing one single line of code, I prefer to change this line of code.

In general we need to take care, that our e2e tests become more stable.  
And we should stick to such simple best practices, e.g. like running e2e tests allways in same resolution on all developer machines, as well as on CI, such that you can have more trust that when it runs on your machine, it will also run on others machines as well as on the CI.

That is why I consider this important and I will solve this soon.

**Comment by bruderol** [comment]
done
