### ISSUE TITLE
Issue Sketcher: Directory path name inconsistent with model

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#478]
There is a "design data directory" but its name is "sketcher" ... this is inconsistent.

Either we call it "sketcher data directory" in our model or rename the directory to "design" or "design-data".

I recommend the later: use "design-data", see ConfigurationRepository.getDesignDataDirectory.

I think this is important to be corrected before the release, because changing the directory name later would be a breaking change.

Probably we should even remove this code and move it directly to SketcherFiles, since we not will make this ever realy configurable (YAGNI).

**Comment by bruderol** [comment]
also in the code there are more such inconsistencies:
e.g. "SketcherFiles" tested in "DesignFilesTest"

**Comment by bruderol** [comment]
I will put some review comments into the code as TODO for this issue in my next pull request for #477

**Comment by bruderol** [comment]
see TODO comments for this issue in my last commit

**Comment by adiherzog** [comment]
@bruderol Thanks for this input. I agree that this should be improved before the release. When cleaning up the sketcher code I already made sure that all sketcher related code is in folders called **"sketcher"**. Therefore we should stick to this name and replace all others like "design" and such.

**Comment by bruderol** [comment]
@adiherzog No, i think we should go the opposite way and use "design-data" consistenty instead (as long as we not are allready inside the sketcher), because it not only contains sketches but also issues. I liked this model that we once discussed and we should keep it. There is one design data container for each branch inside 'design-data", makes sense somehow. Currently it contains issues and sketches, which is called "design domain" isnt it?

**Comment by adiherzog** [comment]
I'll have a look into the naming. The really important things are the design data folder name and the REST URL names, as we should not change them later for backwards compatibility.

@bruderol Regarding the PNG file name: We use the REST service with two different file names, once for the sketch and once for the original screenshot:

* .../rest/branch/wikipedia-docu-example/issue/32221d2f/scenariosketch/90defd20/stepsketch/1/image/sketch.png
* .../rest/branch/wikipedia-docu-example/issue/32221d2f/scenariosketch/90defd20/stepsketch/1/image/original.png

Is that ok or would you still change it? I could also just improve the documentation of the REST endpoint.

**Comment by bruderol** [comment]
can we discuss that on monday please? I think more easy to discuss and find the best solution fast together face-to.face.
