### ISSUE TITLE
Build-Selection: Display name for builds in build selection

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#482]
Every build has a field name, this should be used also as the display text, as for all other objects where the name is used. I do not know why we decided to use revision as the display text (probably because some project liked this idea more). But in general to be consistent, I would prefer to display the name and then each project can decide on what to put into the name (that's their responsibility, not ours).

Reasons:

In my project I would like to use the jenkins build number as the display text for a build, such that a user can easily select the scenarioo reports belonging to a specific build run, for error analysis.

Now I would have to put this information into the revision field, but this does just not make sense, there I would want to put our tested software version (git version) which is much more ugly to display in the build selection and does not say much to a user.

So I think we should realy change that!

@adiherzog do you agree? 
@Fredericson why didnt we use the name instead of the revision as a display text?

**Comment by bruderol** [comment]
I started to change that for Release 2.2 - seems to be very easy and we would finaly be consistent to display the `name` for all objects consistently, as discussed and agreed with @adiherzog

**Comment by bruderol** [comment]
Ok, done, seems to work, I will commit and push

**Comment by bruderol** [comment]
@adiherzog can you shortly review - if you think it is okay, we can close that.

**Comment by adiherzog** [comment]
Looks good and I agree with the change. Thanks for fixing it.
