### ISSUE TITLE
Configure build comparison

### ISSUE THREAD

**Issue by magitnu** [scenarioo/scenarioo#483]
As an administrator, I want to configure how a build gets compared, so that I can customize the Diff Feature for our project.

Acceptance criterias:
- It is possible to configure the comparable builds
- It is possible to select "latest build" as comparable build
- The User can choose which of the precalculated comparable builds he wants to display
- It is possible do disable the Diff Feature

**Comment by bruderol** [comment]
I think we can close this? 
just a duplicate of #484 - right?
@danielsuter  ?

**Comment by danielsuter** [comment]
Looks like. I'm not sure if a gui is meant. Le'ts leave it closed.

**Comment by bruderol** [comment]
we can open a new one for a UI.
