### ISSUE TITLE
Detect use case changes

### ISSUE THREAD

**Issue by Dogen91** [scenarioo/scenarioo#492]
As a user, I want to detect if a use case has changed, is added or removed, so that I can see immediately which use cases are affected by changes.

**Acceptance criterias:**
-	If a use case has no changes a check icon is displayed 
-	If a use case has changes an exclamation icon is displayed
-	If a use case is added a plus icon is displayed
-	If a use case is removed a minus icon is displayed and the row within the use case is grayed out

**Testcases:**
-	All base use cases are equal to the comparison use cases ==> check icons are displayed on all use cases
-	Something below an use case has changed ==> an exclamation icon is displayed on the corresponding use case
-	The base build contains a new use case ==> a plus icon is displayed  on the corresponding use case
-	The base build does not contain all use cases of the comparison build ==> a minus icon is displayed on the corresponding use cases. The use cases are grayed out and not clickable.

**Comment by Dogen91** [comment]
Implemented use case changes.

![usecases](https://cloud.githubusercontent.com/assets/5638334/14809589/58d1d25e-0b8e-11e6-8bee-8f4dd4ff3b35.PNG)

**Comment by bruderol** [comment]
see other user stories. the styling is not final (work in progress by our ui designers), and the exclamation mark needs to display a percentage number. 

I like all the rest, great! :+1:
