### ISSUE TITLE
Detect scenario changes

### ISSUE THREAD

**Issue by Dogen91** [scenarioo/scenarioo#499]
As a user, I want to detect if a scenario has changed, is added or removed, so that I can see immediately which scenarios are affected by changes

**Acceptance criterias:**
-	If a scenario has no changes a check icon is displayed 
-	If a scenario has changes an exclamation icon is displayed
-	If a scenario is added a plus icon is displayed
-	If a scenario is removed a minus icon is displayed and the row within the scenario is grayed out

**Testcases:**
-	All base scenarios are equal to the comparison scenarios ==> check icons are displayed on all scenarios
-	Something below a scenario has changed ==> an exclamation icon is displayed on the corresponding scenario
-	The base use case contains a new scenario ==> a plus icon is displayed  on the corresponding scenario
-	The base use case does not contain all scenarios of the comparison use case ==> a minus icon is displayed on the corresponding scenarios. The scenarios are grayed out and not clickable.

**Comment by Dogen91** [comment]
implemented scenario changes.

![scenarios](https://cloud.githubusercontent.com/assets/5638334/14818581/36b75bdc-0bbe-11e6-81ec-1a0717959b2f.PNG)

**Comment by bruderol** [comment]
final styling still work in progress, I will send you the styles form the ui designers as soon as possible

exclamation mark will be replaced by a percentage display on how much percentages of the content changed.

**Comment by bruderol** [comment]
I like so much the nice description of your user stories! Very good :+1:
