### ISSUE TITLE
Show use case change details

### ISSUE THREAD

**Issue by Dogen91** [scenarioo/scenarioo#500]
As a user, I want to display further detail information about a use case, so that I see if a scenario has changed, is added or removed.

**Acceptance criterias:**
-	If a user hovers over a diff info icon a tooltip with more information is displayed

**Testcases:**
- A user hovers over a check icon ==> The text “This use case has no changes” is displayed in the tooltip
- A user hovers over an exclamation icon ==> For example the following information is displayed in the tooltip: 2 Scenarios changed, 1 Scenario added, 0 Scenarios removed
- A user hovers over a plus icon ==> The text “This use case has been added” is displayed in the tooltip
- A user hovers over a minus icon ==> The text “This use case has been removed” is displayed in the tooltip

**Comment by bruderol** [comment]
I not like to see "0 Scenarios removed", in that case no text should be displayed for "Scenarios removed" instead.

**Comment by bruderol** [comment]
the exclamation icon will also display a percentage number, so the text on exclamation icon should be something like "30% of content of usecase changed, 2 scenarios are affected, 1 added".

I will send you the icons and styles as soon as possible, still work in progress

**Comment by Dogen91** [comment]
implemented with taking care of the criterias from @bruderol . thanks for that.

Example tooltip for a use case which has 1 scenario added, 1 removed and 0 changed.
![tooltip](https://cloud.githubusercontent.com/assets/5638334/14823267/28947aa8-0bd2-11e6-9384-242f6cd21025.PNG)

**Comment by bruderol** [comment]
I will talk to the UI designers today and will send you their stylings.

**Comment by bruderol** [comment]
@Dogen91 do you have a demo build allready, as we have for all our branches (such that we could regularily try out and review what you have allready implemented)?? @danielsuter Please let me know if there are problems with setting this up, I might help in the absence of @adiherzog, i fneeded, should be quite easy.

**Comment by bruderol** [comment]
Sorry, I was not precise enough in my last feedback. The idea was the following:
* display the percentage number directly in the cell of the table ("! 30%")
* popup text: "30 % of content changed, 4 scenarios changed, 1 added" (and implicitly this would mean that none has been removed).
What do you think?

So from a model point of view, you need following informations for each object in a diff:
* changedRatio: 0.0-1.0
* itemsAddedCount
* itemsRemovedCount
* itemsChangedCount

We still need to define how we could calculate the `changedRatio` on any object having subitems beeing compared, and I propose to use something like this:
```
( sum(changedRatio of all sub items) + itemsRemoved ) / numberOfSubItemsInOriginalBaseVersionOfTheObject
```

I would ignore items added for the changedRatio calculation, and instead display a slightly different "!"-icon, when items have been added inside an object. 

What do you think about this proposal?

**Comment by bruderol** [comment]
Hi @Dogen91 

I finally discussed the styling proposal with our UI Designers. You can find a not yet final example here: 
https://github.com/scenarioo/scenarioo/blob/develop/scenarioo-client/resources/scenariooDiffViewerStyles.html 

You have to browse the file locally to see the styling (seems like rawgit.com blocks external links somehow).

This might need some improvements: e.g. refactor most inline styles (except for the width percentage of course) and maybe could be also optimized a little bit, but in general works. Also the colors of the plus and the minus icon need to be adjusted probably. 
But I think the rest is quite nice.

@adiherzog @danielsuter what do you think?

Let's discuss this example, optimize it slightly and then integrate it in the diff viewer.

Many kudos and thanks to @romanrast and @wabaki for their support and great ideas for creating this styles.

**Comment by Dogen91** [comment]
as discussed last week i made three proposals for the "diff icon legend" in the tooltips.
here are the three variants:
![tooltip_1](https://cloud.githubusercontent.com/assets/5638334/15476003/21eddb72-210d-11e6-899e-3f91227ddfcf.PNG)
![tooltip_2](https://cloud.githubusercontent.com/assets/5638334/15476005/21faa208-210d-11e6-9e01-1b1bd63e7eed.PNG)
![tooltip_3](https://cloud.githubusercontent.com/assets/5638334/15476004/21f20a9e-210d-11e6-9c8a-842b210ac7fe.PNG)

i checked the contrast of the colorized text and its background with http://contrastchecker.com/
the result was, that the red font on black color isn't WCAG AAA compatible.
in my opinion variant 3 fits the best because we have the colors in the tooltip and also the text in a very good contrast.

@bruderol @danielsuter what do you think?

**Comment by danielsuter** [comment]
I like both variant 2 and 3. Imho choose the one you prefer.

**Comment by bruderol** [comment]
I like all variants, I would choose variant 2, but variant 3 would also be okay for me, if you prefer it.
