### ISSUE TITLE
Tooltips not working after angular bootstrap update

### ISSUE THREAD

**Issue by Dogen91** [scenarioo/scenarioo#501]
While implementing the detail information for a use case (https://github.com/scenarioo/scenarioo/issues/500) i noticed that the tooltips are no longer working in scenarioo. 
My analyse resulted in the update of the angular bootstrap version to 1.2.2.
Since angular bootstrap version 0.14.0 the tooltip directive is called uib-tooltip.

May i ask you to replace the tooltips with the new directive?

**Comment by bruderol** [comment]
you can replace it wherever you need it

**Comment by danielsuter** [comment]
Fixed with issue #514 . Tooltips now need the prefix uib-. This does not apply for the tooltip placement.
