### ISSUE TITLE
Choose comparison build

### ISSUE THREAD

**Issue by Dogen91** [scenarioo/scenarioo#504]
As a user, I want to choose which pre calculated diff information should be displayed, so that only differences between the current (base) build and the chosen comparison build get displayed.

**Acceptance criterias:**
-	Only the diff information of the chosen comparison build are displayed
-	The Browser should remember the chosen comparison build. So that it is preselected even if the user reloads his session
-	All comparison builds on which a comparison has been done are selectable by the user
-	A comparison build is displayed by its configured comparison name
-	The change rate of a comparison build is visible in the selection menu

**Testcases:**
-	There are two comparison builds (Last Successful and Release 1.0) available for the currently selected (base) build ==> the menu displays two selectable entries (Last successful and Release 1.0)
-	There aren’t any comparison builds available for the currently selected (base) build ==> the menu is empty and no diff information are displayed
-	A User selects the comparison build (last successful) ==> the diff information for the selected comparison build are displayed and the browser persists the selection
-	A User has selected a comparison build and executes a page reload ==> the previously selected comparison build is preselected and the corresponding diff information is displayed

**Comment by bruderol** [comment]
What is missing:
* if no comparison is available
    * then the dropown for comparison is not displayed
    * all pages look and behave exactly the same as before
* if comparisons are available, but none is selected:
   * the user sees in the closed dropdown, that there are comparisons to select from and what the maximum found change rate over all available comparisons is, in its current context (e.g. maximum change rate for current selected use case or scenario or step)
* the change rates in the dropdown selection should be styled similar to the change rates styling in the tables: see http://htmlpreview.github.io/?https://github.com/scenarioo/scenarioo/blob/develop/scenarioo-client/resources/scenariooDiffViewerStyles.html 
* in general the change rates displayed in the dropdown are not just the overal change rate of the whole build, but depending on current context (selected use case, scenario, page, step) the change rate of that selected context/object

I would recommend to rather use just "comparison" and not "comparison build" as wording for the items selectable in the list. One Comparison is a comparison beetween the currently selected build and a "base build" and all its contained objects, so just "comparison" is a good name, I thing, right?
