### ISSUE TITLE
Sort by change rate value

### ISSUE THREAD

**Issue by Dogen91** [scenarioo/scenarioo#508]
As a user, I want to sort the lists „Use Cases“ and „Scenarios“ by change rate value, so I can review the entries with the most serious changes in no time.

**Acceptance criterias:**
-	It is possible to sort (ascending and descending) the use case table by the change rate value
-	It is possible to sort (ascending and descending) the scenario table by the change rate value

**Testcases:**
-	A table is sorted by change rate value ascending ==> the entries at the top of the table have the lowest change rate value. The entries at the bottom of the table have the highest change rate value. For example: first entry: use case with no changes, second entry: use case with a change rate of 55%, third entry: an added use case, fourth entry: a removed use case
-	A table is sorted by change rate value descending ==> the entries at the top of the table have the highest change rate value. The entries at the bottom of the table have the lowest change rate value. For example: first entry: a removed use case, second entry: an added use case, third entry: use case with a change rate of 55%, fourth entry: use case with no changes

**Comment by Dogen91** [comment]
use case and scenario tables can now be sorted by its change rate values.

**Comment by bruderol** [comment]
:+1: would be great if we could have a look at a demo soon.
