### ISSUE TITLE
Fix display of undefined step name

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#520]
![undefined_in_step_name](https://cloud.githubusercontent.com/assets/3780183/15108733/d7bedb40-15d7-11e6-8755-6419aa0b9a13.png)

**Comment by bruderol** [comment]
@danielsuter 
Thank you so much.

Your comment suggests, that the field would better be named `name` as the display text for all other objects we have.

@adiherzog @danielsuter  What do you think sould we rename `title`to `name` in format 3.0 to be more consistent here?

**Comment by danielsuter** [comment]
Name is fine for me.
