### ISSUE TITLE
Leftovers from Release 2.2

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#521]
As defined in my own text file.

**Comment by bruderol** [comment]
@adiherzog can you let us know a little bit more? Are there left overs? Can I help?

**Comment by adiherzog** [comment]
@bruderol This is very very minor stuff, nothing to worry about. I will
just do that one day.
Am 11.05.2016 20:40 schrieb "Rolf Bruderer" <notifications@github.com>:

**Comment by adiherzog** [comment]
I fixed the things I wanted to fix (see linked commits).

**Comment by bruderol** [comment]
Thanks a lot! :+1:
