### ISSUE TITLE
Remove support for IE 8 and older from index.html

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#533]
We still have some code for old IE versions that we don't have support anymore. We should remove that to clean up the index html file.

At the same time we should define which versions of IE we should actually support and figure out how we can test them before releases.

**Comment by adiherzog** [comment]
Angular dropped support for IE 8 in version 1.3 and we are using version 1.5 now. So IE 8 is out. See https://docs.angularjs.org/guide/ie, which also has important hints regarding IE 9 and 10 compatibility.

Therefore I propose to support the following browsers:

* IE 9 and IE 10: We fix bugs if reported, but we don't actively test with these browsers.
* IE 11, Latest Chrome, Latest Firefox: We test with these before releases

@bruderol Do you agree? Then I would add this to the wiki.

I am going to remove all code that is only for IE 8 and below from index.html.

**Comment by adiherzog** [comment]
I removed all extra code for IE 8 and older except for one warning that these users should upgrade their browser.

**Comment by bruderol** [comment]
Cool :+1: Thanks a lot!
