### ISSUE TITLE
Legend of DiffViewer not showing

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#543]
There was once a Legend for DiffViewer Information implemented by students, it seems to be broken (I do not see it).

As described in #500 (in comments)

@danielsuter please have a look. Thanks!

**Comment by bruderol** [comment]
@danielsuter See my commit above. I think i have seen the problem during review and tried to fix it with this commit.

**Comment by bruderol** [comment]
@danielsuter: one problem I see, the branch that we are merging, is probably not the branch that is currently tested on CI for this fork, or is it? Otherwise i could have tested my bugfix (sorry did not have time to test it locally)

**Comment by bruderol** [comment]
@danielsuter I think we can close that. My bug fix seems to have solved the problem. Agree??

**Comment by danielsuter** [comment]
I see you're in a hurry :) Yes I agree.
