### ISSUE TITLE
DiffViewer: GraphicMagick Status Display

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#545]
Same as for Elastic Search there should be an information about graphicMagick Status on Configuration page with a link to the Documentation about how to install it properly, in case GraphicMagick is currently not available.

**Comment by danielsuter** [comment]
@bruderol 
Please comment on my PR. Architecture is not clear to me yet.

**Comment by bruderol** [comment]
@danielsuter Let's resolve this shortly in pair programming tomorrow - I think that will be easy to "warm up" ;-)

**Comment by bruderol** [comment]
done
