### ISSUE TITLE
Scenario Overview: Inside an added scenario steps are not reported as "added"

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#546]
Example see here:
http://demo.scenarioo.org/scenarioo-fork-diffviewer/#/scenario/SwitchLanguageUserInterfaceTest/search_article_in_german_and_switch_to_spanish?branch=wikipedia-docu-example-dev&build=last%20successful&tab=usecases&comparison=To%20last%20successful%20(dev)

This is an added scenario.

Inconsistency: On each step page a step is displayed as "added" but not on the scenario overview page.

**Comment by danielsuter** [comment]
This seems to be the case for all added scenarios. The expectation would an added label be, right?

**Comment by bruderol** [comment]
I am not sure if an "added" label is correct in that case (in my oppinion not optimal as well).
but: at least it would be consistent with how we display it in the step view.
So short answer: yes, unless we define to treat added scenarios differently. 😄

**Comment by danielsuter** [comment]
@bruderol Please verify my PR.

**Comment by bruderol** [comment]
tested and seems to be ok
