### ISSUE TITLE
Step Comparison: Legend for highlighted changes

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#547]
Legend "highlighted changes" should be only displayed ...
1. only over the screen that realy has highlighted changes (not over both!)
2. only if "show highlights" is turned on

![image](https://cloud.githubusercontent.com/assets/755721/19421273/33a15c28-93fd-11e6-96a2-c5e38cbb6ff9.png)

**Comment by danielsuter** [comment]
Please review.

**Comment by bruderol** [comment]
done, tested, seems to be good 👍 Thanks!
