### ISSUE TITLE
Step Comparison: Buttons for toggle single page view

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#548]
I think the button for toggeling between base and comparison screen should appear directly right to the "single page view" button, because that is the most important button for this view, that you usually need immediately after activating the "single page view".

![image](https://cloud.githubusercontent.com/assets/755721/19421298/c7a43274-93fd-11e6-9e5c-55d5eacd4f8e.png)

**Comment by bruderol** [comment]
@danielsuter Maybe a "low hanging fruit"?

**Comment by danielsuter** [comment]
Yes you may move the html code :smile:

**Comment by danielsuter** [comment]
Done.

**Comment by bruderol** [comment]
Thanks 👍
