### ISSUE TITLE
Step Comparison: for no changes

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#549]
The comparison view might be very confusing for those cases where there are no changes to highlight.

In those cases, I think we should disable the button to show highlights.

Same is the case for an added step.

**Comment by bruderol** [comment]
@danielsuter Maybe a "low hanging fruit"?

**Comment by danielsuter** [comment]
Implemented that feature. Now e2e tests only work if graphics magick is available.

**Comment by bruderol** [comment]
alright

**Comment by bruderol** [comment]
does not work for added steps and I still think it is important to display in that case a text "no changes" next to the disabled button!

**Comment by danielsuter** [comment]
Ok, I'll fix that before our release.

**Comment by bruderol** [comment]
@danielsuter done??

**Comment by bruderol** [comment]
I assume this is done.
