### ISSUE TITLE
Some code snippets hard to read in Tutorials

### ISSUE THREAD

**Issue by mspringma** [scenarioo/scenarioo#551]
In http://scenarioo.org/tutorial.html, there are quite a number of code snippets that are hard to read, e.g. the git and gradle commands only get really readable when selecting them so the background changes from black to white.

Also the line numbers in the code example of  "Writing use case and scenario information" and "Writing step information" seem to be messed up (per method insteda of file?!) and have plenty of empty lines in the end.

**Comment by bruderol** [comment]
yes, there is a lot of room for improvement in this part ... it is on our todo list, but not highest prio.

**Comment by bruderol** [comment]
@mspringma Please do not hesitate to contact us directly, if you need some help with using Scenarioo. The documentation is far from optimal.

**Comment by bruderol** [comment]
this will be addressed soon - as we plan to move the tutorial from webpage to our more nicely formatted gitbook docu

**Comment by ideco** [comment]
Tutorial has been moved to: http://scenarioo.org/docs/master/tutorial/Quickstart-Java.html
The snippets are formatted in a readable way now.

**Comment by bruderol** [comment]
@ideco thanks for closing!
