### ISSUE TITLE
Markdown Documentation

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#554]
Acceptance Criterias
- wiki migrated to markdown files (done)
- only one folder "docs" (done)
- better structure of docs folder (done)
- no "end user guide" (just "user guide", done)
- all links inside docu adjusted to new structure (done)
- add links to the web app that point to the correct version of the docu
  - in about dialog (done)
  - in config sections for special features (done for full Text Search)
- adjust external links to the docu
  - from webpage (prepared for release)

**Comment by bruderol** [comment]
@danielsuter @adiherzog 
Hab mir mal die Doku etwas angeschaut.
Finde wir müssen da ein wenig aufräumen.

Aktuell haben wir viele Orte wo Dokumentation abgelegt ist (Wiki, schon 2 Ordner mit Markdown Doku, Tutorial auf Webpage, etc.). mindestens das Wiki wollen wir los werden.

In der neuen Markdown-Struktur haben wir auch schon mindestens zwei verschiedene Strukturen die wir konsolidieren müssen:
1. Adrian hat ein Struktur nach Zielgruppe eingeführt (setup, use, contribute, ...), in jedem dieser Unterordner findet man dann zu jedem Feature entsprechende infos (bisher aber nur für Volltextsuche)
2. Die Studenten haben alles zu DiffViewer in einem Folder abgelegt.

Ich finde beide Strukturen haben Vor- und Nachteile. In jedem Fall müssen wir uns auf etwas einigen.

Ich persönlich bin kein Fan von unnötig zerstückelten und künstlichen Strukturen mit vielen Unterordnern und vielen kleinen Files, wenn wir noch gar nicht viel Inhalt dazu haben. Das ist "up front"-Design und sollten wir, wie auch in der Software, eher vermeiden. Es ist auch nicht angenehm für den Leser, wenn er zwischen vielen Markdown Files hin und her springen muss. Längere Files (wie wir es auch in der Format-3.0-Doku gemacht haben) haben aus meiner Sicht viele Vorteile und sind eher zu bevorzugen. Weshalb ich die Struktur von Adrian im Moment eher für übertrieben halte. Wobei ich natürlich den grundsätzlichen Einstieg (Übersicht für Administratorem , Übersicht für Entwickler, Übersicht für Benutzer) natürlich klar unterstütze! Deshalb mein folgender Vorschlag für die neue Struktur.

Was ich vorschlagen würde:
* 1 File README.md mit der Einleitung und Verlinkung auf Unterkapitel, das ist wohl klar.
* 1 File setup.md mit Setup-Instructions, dieses File kann und soll dann für spezielle Features auf zusätzliche Setup-instructions des Features im entsprechenden Feature-Unterordner verweisen, wo nötig (ich finde es aber fast idealer, wenn grad alles in einem File steht, man kann bei Makrdown auch problemlos auf Unterkapitel eines Files verlinken)
* 1 File USER_GUIDE.md mit User-informationen, wie man Scenarioo verwenden kann (wobei ich mich frage, ob wir das überhaupt brauchen, weil die Scenarioo Webapp möglichst selbsterklärend sein soll)
* 1 File CONTRIBUTE.md mit Informationen für Entwickler und Contributors, auch dieses File kann bei Bedarf auf spezielle weiterführende technische Dokumentation verweisen, ev. gibt es dann einen speziellen Unterordner `developer-guide` dazu.
* 1 Folder `features` mit Unterordnern zu jedem Feature, wo wir gezielte zusätzliche Doku zu jedem Feature ablegen können (test cases, ausführliche technsiche Infos, Glosar, User Guide, etc.), die anderen Hi-Level-Dokumente können bei Bedarf darauf verweisen (z.B. könnte im setup Dokument einfach erwähnt sein, dass man die Volltextsuche separat konfigurieren und installieren muss und dann auf das entsprechende Setup-Dokument verwiesen werden)

Ich finde dass diese Struktur auch praktischer ist, wenn wir weiterhin Arbeiten mit Studenten machen, da diese dann alles zu ihrem Feature in einem entsprechenden Unterordner dokumentieren können und wir dann darauf wo nötig verlinken können.

Was meint ihr?

Ich fange jetzt mal an die bestehenden Wiki-Seiten in eine solche Struktur zu integrieren und die aktuellen zwei Strukturen in den Markdown-Files damit zu konsolidieren.

**Comment by bruderol** [comment]
Ich hab jetzt mal folgendes gemacht:
1. Ich hab alle Wiki Seiten in die Markdown Doku Struktur übernommen. Das war wirklich einfach, das Wiki ist ja auch nur ein Verezichnis von Markdown Files) und hat erstaunlich gut rein gepasst, gar nicht so schlimm wie befürchtet.
2. Dabei hat sich vor allem herausgestellt, dass der Folder "use" nicht wirklich sinnvoll scheint. Ich denke "feature" passt besser, hier beschreiben wir grundlegende Konzepte und alle Features. Lustig war, dass bereits Adrian den Titel im README als "Features" hatte und auch die Beschreibung in diesem File entsprechend besser zu dem passt, was jetzt so im Folder "features" drin ist (und das für mich nicht nur "use" ist).
3. Die Testcases ("specification by Example") zu einem Feature gehören für mich auch in seinen Feature-Ordner ---> siehe entsprechender Ordner für "full-text-search".
4. DiffViewer entsprechend in den "features" fodler übernommen
5. In Setup instructions habe ich DiffViewer und Full-Text-Search neu entsprechend verlinkt.
6. Ich hab alle Cross-References so weit wie möglich versucht zu korrigieren und richtig zu machen.

@adiherzog @danielsuter Ich denke, diese Struktur passt nun so ganz gut, was meint ihr?

Ich mache noch einen Pull Request, dann könnt ihr das reviewen und Feedback geben.

Ist alles auf einem Feature Branch: 
https://github.com/scenarioo/scenarioo/tree/554-markdown-documentation/docs

**Comment by bruderol** [comment]
Hab jetzt auch noch die Doku aus der App verlinkt (mit versioniertem Link auf den jeweiligen Release-Branch), sowohl in der About-Box als auch im Full Text Search Config Abschnitt.

Dazu hab ich alles was mit Versions-Nummern im Server zu tun hatte, grad mal aufgeräumt, damit das alles aus dem build-Skript befüllt wird, was mehr Sinn macht (das Bild-Skript hatte vorher extra eine Java-Klasse nach der internen Format-Version gescannt, das macht irgendwie wenig Sinn).

**Comment by danielsuter** [comment]
Wir sollte noch Index Files hinzufügen. Der Diff Viewer ist nirgends verlinkt. Ich kann daran auch noch arbeiten, aber nächste Woche bin ich komplett ausgebucht.

**Comment by bruderol** [comment]
Ja, klar, an der Verlinkung und Struktur können wir noch weiter arbeiten. Ev. lohnt sich gar ein Setup von gitbook Tooling (machen wir grad in meinem Projekt). Da die Struktur aber auch so im File Tree browsbar ist, sehe ich da keinen dringenden Need. Etwas unsicher bin ich noch, ob wir jeweils zwischen README.md und SUMMARY.md unterscheiden sollten. Das hab ich ev. nicht ganz richtig gemacht. Könnt ihr gerne verbessern. Ich schlage trotzdem vor, dass wir das mal so mergen und dann weiter daran ikrementell weiter arbeiten.

**Comment by bruderol** [comment]
Siehe hier, ich denke, wir sollten uns an die von gitbook vorgeschlagene Grundstruktur halten, d.h. dann wohl, dass das README.md üblicherweise die Übersicht zu jedem Kapitel enthält (Meta-README ist aus meiner Sicht nicht zwingend nötig, wenn die Struktur an sich auch so für alle selbsterklärend ist):
https://toolchain.gitbook.com/structure.html

**Comment by adiherzog** [comment]
@bruderol @danielsuter Looks good, I merged it. 

We should discuss where excactly we draw the line between setup and features. Shall we put configuration options of features into the setup folder or the feature folder? I think under "setup" we should at least describe all options in the config file and all optional dependencies (Graphics Magick, etc.). Or do you think the "setup" folder is just for the initial setup and everything else should be in the "features" folder?

**Comment by bruderol** [comment]
Yes, exactly, I think we should rather go for a structure where you find everything belonging to a feature in one place (better for reference and for maintaining the docu, because you find everything about one topic in one place), and then link to there from the setup instructions, how it is done now.
Or what concrete real problem do you see with this structure?

**Comment by adiherzog** [comment]
Yeah, that sounds reasonable to me. Having the details in the features and linking from the setup instructions to the features makes sense.

**Comment by danielsuter** [comment]
@bruderol 
Bitte Wiki Links vom Hauptreadme löschen und den Wiki Branch auch gleich löschen.

**Comment by danielsuter** [comment]
@bruderol 
Contribute Links funktionieren noch nicht.

**Comment by bruderol** [comment]
@danielsuter Das Wiki können wir erst nach dem Release löschen. Da es noch die aktuell gültige Doku enthält!

**Comment by bruderol** [comment]
@danielsuter but I am working on your other points and will improve the docu.

**Comment by bruderol** [comment]
I will also try to remove some redundancies in our docu

**Comment by bruderol** [comment]
@danielsuter @adiherzog See https://github.com/scenarioo/scenarioo/pull/557 and please review and merge it!

**Comment by bruderol** [comment]
@adiherzog @danielsuter 
Allmost done, just links from webpage are missing.
Do you know of other problems with current docu?
Everybody ok, when I remove the Wiki after the release?

**Comment by danielsuter** [comment]
Yes.

**Comment by adiherzog** [comment]
Yes

**Comment by bruderol** [comment]
Last open point: remove wiki after release

**Comment by bruderol** [comment]
deactivated our wiki, no wiki anymore :-)

**Comment by bruderol** [comment]
prepared linking new markdown docu on webpage:
https://github.com/scenarioo/scenarioo.github.io/pull/1

Will merge that now.

**Comment by bruderol** [comment]
@adiherzog @danielsuter 
I removed/deactivated the wiki and the new markdown documentation is linked in our tutorial on the webpage as well as all other important documentations for all writer libraries.

Will close this issue now.
