### ISSUE TITLE
URL for new relatedSteps REST endpoint

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#558]
Change URL of new REST API service for screenshots of steps related to any object:

URL currently is:
/rest/branch/{branchName}/build/{buildName}/object/{type}/{objectName}/relatedstep

should be:
/rest/branch/{branchName}/build/{buildName}/object/{type}/{objectName}/steps

because it returns all steps (a collection) and not just one object.

**Comment by bruderol** [comment]
@featureenvy I hope you agree? Problem for your project if we change that?

**Comment by featureenvy** [comment]
This is not a problem, I can update the other tool accordingly.

**Comment by bruderol** [comment]
ok, I will change that

**Comment by bruderol** [comment]
Changed and merged it, also cleaned up code a little bit (mainly naming!)

**Comment by bruderol** [comment]
@featureenvy: the new URL of the service is now /rest/branch/{branchName}/build/{buildName}/object/{type}/{objectName}/steps` please merge and adjust in your project! Thanks!

**Comment by featureenvy** [comment]
I will update once we deploy the latest version. Thanks!
