### ISSUE TITLE
Search indexes get lost

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#565]
On the demo the search indexes are allmost never available, it seems they dissapear ...

![image](https://cloud.githubusercontent.com/assets/755721/20327349/f67d2230-ab8c-11e6-9c4b-c8fed379545c.png)

**Comment by adiherzog** [comment]
@bruderol The reason for the problem was that the disk was almost full. Now we deleted some files and limited the "builds to keep" from 20 to 10.  This should prevent filling the disk in the future.

**Comment by bruderol** [comment]
@adiherzog: does Elastic-Search remove indexes when there is no space left? Or why did it work after reimporting a build? I would have expected, that if the disk was full, it did not work at all. Are you sure this was the real root cause of the problem?

**Comment by adiherzog** [comment]
@bruderol Looks like the index got lost again. Have to investigate again.

**Comment by bruderol** [comment]
does not surprise me - I was almost sure this has nothing to do with the disk size, because the indexes are sometimes there and the next morning they are gone again. does a index have a lifetime?

**Comment by adiherzog** [comment]
I think I found the issue. There's some code that removes indices that do not have a corresponding build in Scenarioo (not sure whether this code actually does the right thing...). The problem is most probably that this removes the indexes of other scenarioo installations as well, which is a problem of the build server. I tried to do a quick fix to prove this is the problem, but now the build suddenly fails.

```
Starting process 'command 'npm''. Working directory: /var/lib/jenkins/jobs/scenarioo-develop/workspace/scenarioo-client Command: npm install
Successfully started process 'command 'npm''
npm WARN package.json scenarioo-client@0.0.0 No README data
npm ERR! addLocal Could not install /tmp/npm-4199-dd65be66/git-cache-10a717a63e0b/328142050c16eee0e039ec6dc975993e54c04296
npm ERR! addLocal Could not install /tmp/npm-4199-dd65be66/git-cache-56e0de284f97/328142050c16eee0e039ec6dc975993e54c04296
npm ERR! git fetch -a origin (git@github.com:scenarioo/scenarioo-js.git) Permission denied (publickey).
npm ERR! git fetch -a origin (git@github.com:scenarioo/scenarioo-js.git) fatal: Could not read from remote repository.
npm ERR! git fetch -a origin (git@github.com:scenarioo/scenarioo-js.git) 
npm ERR! git fetch -a origin (git@github.com:scenarioo/scenarioo-js.git) Please make sure you have the correct access rights
npm ERR! git fetch -a origin (git@github.com:scenarioo/scenarioo-js.git) and the repository exists.
npm ERR! Linux 3.13.0-24-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code 128

npm ERR! Command failed: git fetch -a origin
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/jenkins/jobs/scenarioo-develop/workspace/scenarioo-client/npm-debug.log
:scenarioo-client:npmInstall FAILED
:scenarioo-client:npmInstall (Thread[Daemon worker,5,main]) completed. Took 4.923 secs.
```

@bruderol @danielsuter Any idea why this suddenly happens?

**Comment by adiherzog** [comment]
@bruderol introduced this issue and also fixed it already, build runs now.

**Comment by adiherzog** [comment]
@bruderol Fixed the issue on the develop branch (hopefully). But indices still get deleted because the `scenarioo-fork-full-text-search` instance still deletes too many indices. We can just remove this war file and disable the build for this fork.

**Comment by bruderol** [comment]
let's just assume, that it is okay now, but there is a test failing, that we need to find out why.

**Comment by bruderol** [comment]
ok now? Can we close?

**Comment by adiherzog** [comment]
Prefixed the indexes with the context. Added `---` as separator in order to make collisions with other prefixes very unlikely so that they don't delete each other's indices.

![image](https://cloud.githubusercontent.com/assets/3780183/20815019/6bb5a7e8-b81c-11e6-83ba-6ba0e47c76f3.png)

**Comment by bruderol** [comment]
Thanks 👍
