### ISSUE TITLE
If GraphicsMagick is not installed, no Exception should be logged

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#571]
Currently if GraphicsMagick is not installed an Exception is logged. This is not necessary as this is a totally valid situation. So we should catch the exception and just log a single line.

![image](https://cloud.githubusercontent.com/assets/3780183/20815605/d2b41982-b81e-11e6-9149-13d6cdbbc96d.png)

**Comment by bruderol** [comment]
@adiherzog thanks 👍

**Comment by bruderol** [comment]
@adiherzog I close this, since with the removal of Graphic Magick this is solved
