### ISSUE TITLE
NullPointerException being logged in diffViewer Comparator

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#577]
I see many exception stack traces of NullPointerExceptions logged as warnings, when running our 
e2e tests with ImageMagick installed.

If this is indeed a Warning (and no real issue), I think that it should not log the whole stack trace but just a warning message. Or if it is a real problem we have to change our e2e test setup, that this can not happen.

**Comment by bruderol** [comment]
@kabl probably this has already been implemented in the PR - please verify and close.

**Comment by adiherzog** [comment]
Closing this as ImageMagick was removed.
