### ISSUE TITLE
Remove bower

### ISSUE THREAD

**Issue by danielsuter** [scenarioo/scenarioo#579]
Use webpack and npm instead of bower for managing frontend dependencies. This will probably also replace some grunt features such as bundling and minifying.

**Comment by bruderol** [comment]
@danielsuter noch aktuell? Erledigt?

**Comment by danielsuter** [comment]
Erledigt.

**Comment by bruderol** [comment]
Top - ich mach ne flasche 🍾 auf! 🎉 das müssen wir feiern! Endlich kein bower mehr! 😀
