### ISSUE TITLE
Demo seems to be down

### ISSUE THREAD

**Issue by feststelltaste** [scenarioo/scenarioo#581]
We wanted to get a first glimpse on scenarioo. Unfortunately it seems that there is no data avaliable on the demo site: http://demo.scenarioo.org/scenarioo-master/#/?branch=wikipedia-docu-example&build=last%20successful&comparison=Disabled&tab=usecases

![2017-01-25 11_30_30-scenarioo demo for master branch](https://cloud.githubusercontent.com/assets/1470822/22287099/d8e58b6c-e2f1-11e6-80da-d5f4c67446c9.jpg)

Browser: Chrome 55.0.2883.87
OS: Windows 7 64-Bit

**Comment by adiherzog** [comment]
Thanks for informing us. Seems somebody changed a setting to a wrong value in the "Manage" tab. I just fixed it and the Demo is available again: http://demo.scenarioo.org/scenarioo-master/

**Comment by feststelltaste** [comment]
Thanks for the quick help!

**Comment by bruderol** [comment]
@feststelltaste thanks for your feedback - would be cool to know what you think about Scenarioo and whether this might be helpful for you. And if you have some wishes or feedback, just let us know here through issues. Thanks a lot!
