### ISSUE TITLE
Docker error when pulling image

### ISSUE THREAD

**Issue by leozulfiu** [scenarioo/scenarioo#589]
I tried the command `docker pull scenarioo/webapp` and get the following error:
```
Using default tag: latest
Error response from daemon: manifest for scenarioo/webapp:latest not found
```
If I execute `docker pull scenarioo/webapp:3.0.0` it works. I guess there is some kind of linking to the latest version for the tag `latest` missing.

**Comment by bruderol** [comment]
We did not ever provide a tag for latest - we recommend to specify exactly which version you want to use.
Also our docu mentions that: http://scenarioo.org/docs/setup/Scenarioo-Viewer-Docker-Image.html
The run command there has the exact version inside, as you can see.

found a good article about it:
https://medium.com/@mccode/the-misunderstood-docker-tag-latest-af3babfd6375#.cjt35m5jg

It also mentions, that this is not recommended to be used.

@leozulfiu @mi-we If you think, we should provide a latest - feel free to reopen this and go ahaead and define one! Thanks!
