### ISSUE TITLE
DiffViewer Improvements - Color of Diff Image

### ISSUE THREAD

**Issue by patrickschweizer** [scenarioo/scenarioo#596]
CR / Feedback from one team using Scenarioo:
Make color of Diff Image configurable

Depending on the background or foreground colors used in a web application, a suitable Diff Image color  can be configured so that the contrast can be optimised to highlight differences.

**Comment by bruderol** [comment]
also the ratio of transparency should be configurable.

the default should be stronger than what we had as old default but a little more transparent and orange than in the current changed implementation on the PR.

@adiherzog @danielsuter this will probably be implemented by @kabl

**Comment by kabl** [comment]
start working here...

**Comment by kabl** [comment]
Merge Request: https://github.com/scenarioo/scenarioo/pull/608

**Comment by kabl** [comment]
@bruderol @patrickschweizer: The new configuration value. Example: ```<diffImageColorRgbaHex>0xc8ff0000</diffImageColorRgbaHex>```
Pattern: 0xAARRGGBB.

In some Sub-Classes of the configuration there also exists Color Properties. They're in the HTML RGB Syntax ```#RRGGBB``` but HTML doesn't support an Alpha Channel.

**Comment by bruderol** [comment]
yes, that looks ok for me. Use whatever fits best for the purpose you need it.

**Comment by kabl** [comment]
PR: https://github.com/scenarioo/scenarioo/pull/609

**Comment by bruderol** [comment]
@adiherzog I think the default should be orange again and more transparent let's say 70% or even less. and also it might be worth to have a look at my last comments on the PR.

**Comment by adiherzog** [comment]
Use stronger orange

**Comment by bruderol** [comment]
I changed it to be the same color as used in other places for changes, and changed the color everywhere to a stronger orange (more red)

**Comment by bruderol** [comment]
I close this, it is now configurable, and the default orange for highlights is slightly stronger than it was before.
