### ISSUE TITLE
Store diff information directly inside build

### ISSUE THREAD

**Issue by patrickschweizer** [scenarioo/scenarioo#597]
CR / Feedback from EBP Team 2017-02

Rolf, Patrick and EBP Team came to the conclusion, that the Diff Images shall be written into the data structure of the currently selected build.

Acceptance criteria
* All Diff Data for Comparisons is stored inside the build on which these Comparisons will be available
    * not in scenarioo-application-directory anymore
    * in a special directory called `comparisons.derived` inside the build
* all unused code regarding calculation of the diff data directory location has been removed

Reasons
- makes it simpler to delete the scenarioo data structure of an old branch/build inclusive diff images
- since EBP is the only team using the DiffViewer feature so far, backwards compatibility can be ignored, it means that after scenarioo update, the diff will have to be recalculated, that should be okay for everybody.

**Comment by bruderol** [comment]
we have to keep in mind,that this is a breaking change. But I think we can make an exception here, since this is only calculated data, that would need recalculation to be available again.
