### ISSUE TITLE
Branch Selection Order

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#601]
The PR #593 contains following change that needs to be slightly changed:
It was changed to order the builds in the build selection list (only the real builds, not the build aliases in front of them) in descending order according to the date of their last build.

Since we expect that some projects might not like that changed behaviour, but we see that this makes sense for some projects, we propose the following solution.

Acceptance Criteria
* this change should not become effective with default config settings
* through an additional config property `branchSelectionListOrder` the following ordering options can be configured:
     * `name-ascending` (=default, if value not set the behaviour is the same): the branches are sorted by name alphabetically (same as before the change was applied and the code to calculate the potentially more slower other ordering is not triggered)
     * `name-descending` (useful for projects that have names with version or release date or stuff like that inside): branches are sorted in descending order according their branch name.
     * `last-build-date-descending`: use the new behaviour that was added in the PR already.
* the branch aliases are in any case displayed at the start of the list and those are always ordered in ascending alphabetical order (as it is already).
* the new config possibility is documented on the setup and configuration documentation pages in our markdown docu
* (optional) the option can be changed on the general settings configuration page of the viewer webapp (only if enough time to implement it)

**Comment by kabl** [comment]
Question: "..through an additional config property.." It's the ".scenarioo/config.xml" file?

**Comment by kabl** [comment]
Is this the ordering function (resp. the change from the PR #593) https://github.com/scenarioo/scenarioo/pull/593/commits/0e68645e998b6564b0699945b8818c9d7bc0f07c#diff-2cf19f7ea8de31b84a9c710d7e6efc60

**Comment by kabl** [comment]
The configuration - ```Configuration.java``` - XML/JSON is exposed through the REST API - ```ConfigurationResource.java```. Could there be side-effects if there is a new property?

**Comment by bruderol** [comment]
no, that is safe - you can add as much new properties as you want, just go for it! it's not the first time we do that. you should just not remove existing ones.

**Comment by kabl** [comment]
Problems: ```branchOrderBy.filter.js```. Changed "constructor".
The test class needs to be adapted ```branchOrderBy.filter.spec.js```

````
PhantomJS 2.1.1 (Mac OS X 0.0.0) Filter scBranchOrderBy should handle invalid input gracefully: string FAILED
        Error: [$injector:unpr] Unknown provider: ConfigServiceProvider <- ConfigService <- scBranchOrderByFilter
        http://errors.angularjs.org/1.5.2/$injector/unpr?p0=ConfigServiceProvider%20%3C-%20ConfigService%20%3C-%20scBranchOrderByFilter (line 4418)
        /Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4418:86
        getService@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4571:46
        /Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4423:48
        getService@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4571:46
        injectionArgs@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4595:68
        invoke@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4617:31
        enforcedReturnValue@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4464:43
        invoke@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4625:24
        /Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4424:43
        getService@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4571:46
        /Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:19193:27
        /Users/a/IdeaProjects/scenarioo/scenarioo-client/test/spec/shared/navigation/branchOrderBy.filter.spec.js:26:40
        invoke@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular/angular.js:4625:24
        workFn@/Users/a/IdeaProjects/scenarioo/scenarioo-client/app/components/angular-mocks/angular-mocks.js:2933:26
        undefined
        TypeError: undefined is not a constructor (evaluating 'scBranchOrderByFilter('someString')') in /Users/a/IdeaProjects/scenarioo/scenarioo-client/test/spec/shared/navigation/branchOrderBy.filter.spec.js (line 31)
        /Users/a/IdeaProjects/scenarioo/scenarioo-client/test/spec/shared/navigation/branchOrderBy.filter.spec.js:31:47

```

**Comment by kabl** [comment]
Diff: https://github.com/scenarioo/scenarioo/pull/607

**Comment by kabl** [comment]
Ready to merge: https://github.com/scenarioo/scenarioo/pull/607

**Comment by bruderol** [comment]
@kabl see my comments on the PR - small corrections needed but most looks great!
And one last thing: can you also already list the new feature in the CHANGELOG for next release.
Thanks!

**Comment by bruderol** [comment]
oh - forget last point - there seems to be no CHANGELOG yet ;-)  - maybe we should introduce one, as we have for https://github.com/scenarioo/scenarioo-js
