### ISSUE TITLE
Remove GraphicsMagick

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#602]
Since the Java implementation of image comparison seems to have too much advantages (better performance, less disk usage for images, highlight changes on both sides) we want to remove ImageMagick completely.

Acceptance criteria
[] new Java impl merged and tested (done)
[] removed in code and dependencies
[] removed in docu
[] removed in dockerfile (image will be republished after next release)

**Comment by kabl** [comment]
Called ```GraphicsMagick```

**Comment by kabl** [comment]
- I didn't find any dependency of GraphicsMagick or *Magick in the Java code. Except the unused class DiffViewerStatus.java
- In JS some small parts there. generalSettings.controller.js
- Docu and Docker have several GraphicsMagick dependencies

**Comment by kabl** [comment]
PR: https://github.com/scenarioo/scenarioo/pull/610
