### ISSUE TITLE
Scenarioo only supports Elasticsearch 2.x, not 5.x

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#616]
Tried to run Scenarioo with Elasticsearch 5.5.1, but it did not work. Going back to 2.4.6 worked.

Will be fixed by #598 - ses #598 for current state and remaining work.

**Comment by bruderol** [comment]
@adiherzog should we fix this??

**Comment by adiherzog** [comment]
@bruderol I would not fix it as long as nobody complains. But let's keep this issue open and let's document it in the full text search feature documentation.

**Comment by adiherzog** [comment]
@bruderol I extended the documentation.

**Comment by adiherzog** [comment]
@til77 Is this an issue for your project? Do you use the full text search at all?

**Comment by bruderol** [comment]
we removed it from our current release plan - as soon as somebody reports that this is an issue in a project - we will try to fix it. please just comment here, if somebody has an issue with this current limitation

**Comment by til77** [comment]
we don't use full text search

**Comment by cgrossde** [comment]
https://github.com/scenarioo/scenarioo/pull/685

**Comment by bruderol** [comment]
@cgrossde well spottet - thanks!

**Comment by bruderol** [comment]
we should focus on #598 and my branch for that isseue first (contains your branch for this issue here)!
