### ISSUE TITLE
DiffViewer: New Internal Data Format

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#618]
For "Diff Viewer Plus" the new data format for calculated comparisons comes with following changes:

already done:
* only a transparent image with the highlights of the changed areas is stored:
   * needs less disk space!
   * can be displayed as overlay over both images

still to be implemented:
* the comparisons are stored in the base build as well, such that comparisons will be removed as well when deleting a build
* see also #597
* maybe configurable to not break for any project? (not really important, since the transparent pictures are allready a breaking change that need recalculation of all diffs)

**Comment by adiherzog** [comment]
Closing, remaining work is in #597.
