### ISSUE TITLE
CI Pipeline Modernisation

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#619]
As a devloper of scenarioo I want to have all our code and release artifacts verified automatically, as well on feature branches, such that I can change whatever needs to be changed on a feature branch and I will get informed by jenkins, if something was broken that needs adjustment.

**Acceptance criterias**
* New pipeline builds and verifies all feature branches automatically
* New pipeline publishes a demo for all feature branches (for further manual testing)
* New pipeline also builds the docker image of scenarioo
* New pipeline uses the docker image of scenarioo for running the e2e tests against it (to also test the docker image)
* New pipeline is versioned in git repository, such that changes needed to the piepline on a feature branch can be done without affecting other feature branches and without having to access jenkins for changing the pipeline.
* New pipeline uses docker image as well for demo:
   * As soon as the docker image was built sucessfully it starts a new container
   * Old container for same branch is stopped
   * Nginx config will be changed to switch to the new container
   * this will be done even if the e2e tests are failing (before they are executed!), such that manual analysis of problems can be done on the demo easily and we do not have to wait for a new demo version until e2e tests are executed. 

**Implementation details**
* New Pipeline is baed on Jenkins Pipeline Plugin, Jenkinsfile checked in
* docker-gen can be used to deploy demos using docker images and nginx, see http://jasonwilder.com/blog/2014/03/25/automated-nginx-reverse-proxy-for-docker/ or https://tutorials.technology/tutorials/30-how-to-use-nginx-reverse-proxy-with-docker.html

**Stories**
* #617 - Build, Run & Test Docker Image
* further sub stories ?? maybe already existing??

**Comment by bruderol** [comment]
@Hofmaier @mi-we @sascha-kaufmann Ich hab mal für Euer "Projekt" dieses Epic hier eröffnet - ich würde euch gerne bitten wieder vermehrt auch in unserem Backlog (=Issues hier) ein wenig zu dokumentieren/kommentieren/diskutieren was schon gemacht wurde und was noch alles ansteht. Ihr könnt das gerne mit Unter-Issues resp. Stories zu diesem Epic hier machen, einfach so verlinken wie das Beispiel hier #617 (Issue von Lukas). Danke :-)

**Comment by cgrossde** [comment]
@bruderol Können wir das schließen?

**Comment by bruderol** [comment]
@cgrossde ich denke ja
