### ISSUE TITLE
Do not reimport comparison, if comparison already exists

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#624]
# Reason

When raising the internal format version, this currently triggers all diffs to be recalculated. We want to avoid this.

# Acceptance Criteria

* [ ] If the comparison folder *and* the `build.xml` inside the comparison folder exists, Scenarioo does not recalculate the comparison.
* As is: If the comparison calculation fails for some reason or is cancelled because something was not found, the comparison folder is created anyway and the log file exists for analysis. The state in the `build.xml` file will indicate the comparison failed. this was already done by @adiherzog.

# Open Points

* Is build.xml only written when diff import is successful?
   * Answer by @bruderol: now it is even written when failed, but user can see this now in new management ui and can then trigger a manual import in case he needs a failed comparison. So I think this is enough.

@adiherzog this has now become easy, thanks your and others changes. I will implement in the run of implementing background jobs for comparisons, which also makes this more important now.

**Comment by adiherzog** [comment]
Now we need to check the state in the XML file instead.

**Comment by bruderol** [comment]
Done as part of PR #696
