### ISSUE TITLE
Don't create comparison directory if comparison is not created / successful

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#626]
# Reason

Comparison folders should only exist for comparisons where there are actually two builds that can be compared. In all cases where there's a comparison configured but no comparison build is found we don't want to pollute the file system with folders that only contain a log file saying no comparison build was found.

# Details

Sometimes the directory is created even thought no comparison build is found:

```
============= START OF BUILD COMPARISON ================
Comparing base build: wikipedia-docu-example/2014-01-20 with defined comparison: To Projectstart
This might take a while ...
No comparison build found for base build: wikipedia-docu-example/2014-01-20 with defined comparison: To Projectstart
SUCCESS on comparing base build: wikipedia-docu-example/2014-01-20 with defined comparison: To Projectstart
Comparison finished in 0 min. 0 sec.
============= END OF BUILD COMPARISON (success) ===========
```

In this case it's probably better not to create the comparison folder so that during a later reimport we try to find the comparison build again. It's possible that the comparison build exists later, e.g. because it was imported in the meantime. So it would be nice if the user can add the missing comparison by triggering a reimport.

# Acceptance Criteria

* Comparison folder is not created when no comparison build is found
* The fact that no comparison build was found for a configured comparison is logged in the regular Scenarioo log file

**Comment by adiherzog** [comment]
This is not true anymore. We will create the folder even in case of failure so that we can store the status in the XML file. Need to reconsider what impact this has on this story.

**Comment by bruderol** [comment]
@adiherzog As long as the log file with the error why the comparison failed is saved, I think this is ok.

**Comment by bruderol** [comment]
Remark: I found some code which means that we only output a warn int hat case and wont create a build result - maybe tro be verified --- I think both would be okay, we just have to verify it does not crash and either shows nothing in the new manage UI for such diffs or it shows them as failed with appropriate log. Both would be ok currently. First behavioud would be preferred.

**Comment by bruderol** [comment]
Current behaviour:
* directory is already created for each comparison being calculated
* for not found comparison buidl only the log is written, but no diff info (at least)
* therefore this data is useless, but would inform, sombody debuggion what really happened, so we think it is okay for now

@adiherzog agreed to keep  it - we close it.
