### ISSUE TITLE
Move tutorial and other docu parts to gitbook docu

### ISSUE THREAD

**Issue by ideco** [scenarioo/scenarioo#629]
- Move tutorial to gitbook
- Change structure of our Docs slightly to fit the new tutorial inside and merge some content (e.g. http://scenarioo.org/docs/setup/How-to-use-Scenarioo-Writer-Library.html) (see TODOs in SUMMARY.md)
- Change "Tutorial" link on homepage to documentation
- Change all other places where Tutorial was linked (check all repos), e.g. https://github.com/scenarioo/scenarioo-java/blob/master/docs/usage.md#tutorial
- Adjust all other links to docu, where the new structure might not fit anymore (take care of paragraph titles changed in the docu, they might be linked with url containing # )
- Also put our video in the introductory docu as well

**Comment by bruderol** [comment]
I want to see this for the next relase - can we make it happen?

**Comment by adiherzog** [comment]
@ideco I made some changes to the website today, e.g. I renamed the menu entry "Tutorial" to "Docs" and added links to the current and the future (develop) version of the documentation there.

**Comment by bruderol** [comment]
Since we used this issue to mostly move all kind of docu into our docu and not to adjust the tutorial to the pizza example - I changed the story accordingly. Will open a follow up story for changing th tutorial to the pizza example

**Comment by bruderol** [comment]
Done
