### ISSUE TITLE
Build Pipeline: Wait for all startup calculations completed and fail fast on error

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#637]
Wait properly and stable for successful server startup before starting e2e tests, and avoid a fixed 2 minutes wait.

Acceptance criteria
* Ensure that tests will never start before server startup (including things like calculation of all diff comparisons) was done and succesful
* If a failure (exception log) occurs during waiting for the success of the startup then the build should immediately stop waiting any further and let the build fail 
* Wait for a well defined log entry that only occurs when all builds have been finished importing and all belonging diff comparisons have finished calculating (put an appropriate message for that into the application such that we can simply wait for this well defined message)

Purpose of thic change:
* currently there is a 2 minute sleep in the build script, that is not guaranteed to wait long enugh and still might often be longer than needed
* we want the build to fail as fast as possible if there occurs an exception during startup or import of builds
* waiting for one well defined startup and import success log entry should also make it more easier to change the things that are calculated during startup, and just waiting for that one well defined log entry (e.g. somewthing like "Scenarioo Startup COMPLETE - All import work COMPLETE") should be everything needed to wait for no matter how the app changes.

**Comment by eggerschwiler** [comment]
This has been resolved.
