### ISSUE TITLE
Migrate E2E Tests to TypeScript

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#646]

**Comment by bruderol** [comment]
Cool - thanks :+1:

**Comment by danielsuter** [comment]
Sorry for duplicating your work. Maybe we can close this issue, since something similar is already merged?

**Comment by bruderol** [comment]
I think this can be closed - @adiherzog please check shortly and then close (and also remove any unneeded branches)

**Comment by bruderol** [comment]
@adiherzog please merge your commit before closing thsi, I think you improved some imports in your commit on the branch, that @danielsuter missed to improve. Thanks.

**Comment by bruderol** [comment]
@adiherzog pleeeaaaassseeeee: can we close or what is missing???
