### ISSUE TITLE
Diff Viewer Plus: Manage Comparisons View

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#650]
# Reason

Currently there's no transparency regarding which Diffs are currently being calculated and which ones are already calculated.

# Acceptance Criteria

* A new tab called "Diffs" is shown in the Manage section of Scenarioo (same structure as the "Builds" tab)
* The section "Diff Viewer" from the "General Settings" tab is moved to the "Diffs" tab
* The "Diffs" tab shows a list of all comparisons that are either in progress or completed / failed, from all branches.
* For each Diff one row is shown with the most important fields (to be discussed).

# Out of Scope

* The diffs configuration can not be configured in the UI
* The diffs configuration is not shown in the UI

**Comment by bruderol** [comment]
@mi-we just let me know, when you need help for the backend ...

**Comment by bruderol** [comment]
@mi-we and @sascha-kaufmann as discussed:

please adjust ComparisonResult as follows ...

// TODO rename to just "changeRate";
private String rmaePercentage;

// TODO additional fields
private ComparisonCalculationState state;
private Date calculationDate;
private Date baseBuildDate;

Then introduce the rest endpoint that returns a list of those, and this list will be read from file comparisons.derived.xml – later we will generate this file in the backend every time a comparison calculation is done or the builds are refreshed.

**Comment by mi-we** [comment]
Note to self to move BuildIdentifier to the model directory since it is used not only as a DTO

**Comment by adiherzog** [comment]
We decided that this is not a MUST for the release 4.0, so we set it to Prio-2.

**Comment by bruderol** [comment]
REST Endpoints to use for this feature: 

to get all calculation results:
/rest/comparisons

to get log of one calculation:
/rest/builds/{branchName}/{buildName}/comparisons/{comparisonName}/log

branch  and build name is from the base build

**Comment by bruderol** [comment]
@sascha-kaufmann @mi-we Thanks for incredible awesome work today - I think we can merge that soon - I like the new UI!! :-) Great!

**Comment by bruderol** [comment]
I think we could merge the PR and close this issue - but @mi-we please merge your remaining improvements for the modal dialog and see my comments on the PR (mostly top description).

Please update my changes on the branch first! (I did a lot of small improvements to the cool new view to make it even cooler! ;-) ).

**Comment by adiherzog** [comment]
The comparisons view does not work on the demo of the develop branch:

http://demo.scenarioo.org/scenarioo-develop/#/manage?branch=Development&build=last%20successful&comparison=Disabled&tab=comparisons

![image](https://user-images.githubusercontent.com/3780183/40328398-82a2e760-5d46-11e8-8996-8a8554c64c76.png)

@bruderol @mi-we @sascha-kaufmann Could you please look into this?

**Comment by adiherzog** [comment]
@bruderol @mi-we @sascha-kaufmann Now the view looks fine on the demo instance: http://demo.scenarioo.org/scenarioo-develop/#/manage?branch=Development&build=last%20successful&comparison=Disabled&tab=comparisons

Seems this was related to the corrupt data from the comparison dialog branch.

**Comment by bruderol** [comment]
I close it - it has been merged
