### ISSUE TITLE
Interceptor for request logging

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#651]
Currently we have no automatic logging of every HTTP request.

We can add this using a simple interceptor.

I did an implementation on the feature branc `feature/605-comparison-rest-endpoint` that looks like this:

![image](https://user-images.githubusercontent.com/3780183/33381072-3a055044-d51d-11e7-93e5-ad8833f3ce70.png)

Advantage: automatic logging, always same format

Disadvantage: values can't be printed in method name

@bruderol Is this acceptable? Can I remove the old manual request logging statements?

**Comment by bruderol** [comment]
I dont know, if there is nothing very special logged for some of the requests, you could remove those general lof statements but there are some very important special logs for some rest calls, and those should be kept.
