### ISSUE TITLE
Improve Step Comparison View Screenshot Captions

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#660]
As user I do not want the screen to get cluttered with the full timestamp and revision above each of the screenshots in comparison view, such that I see more clearly the most important information (which screenshot is which build) and the layout does not get broken even on smaller screens too fast.

Acceptance criteria
* each screenshot caption starts with short prefix:
    * "Current:" for current screenshot of current selected build
    * name of the selected comparison for the screenshot of the other build that it is compared to
* behind this prefix only the name of the build (and if available the alias of the build) is displayed above each of the screenshots followed by an information icon, to make it obvious that there is more information about the build that can be showed in tooltip over that icon.
* Less important information about each screenshot like timestamp  and revision is only displayed in tooltip over the information icon

**Comment by bruderol** [comment]
@adiherzog I improved it - looks now as follows:

![image](https://user-images.githubusercontent.com/755721/34641736-e8da1a60-f308-11e7-87d1-b43e55462fe2.png)

**Comment by adiherzog** [comment]
@bruderol Well done, I like it!
