### ISSUE TITLE
ElasticSearchSearcher does not use configuration of config.xml

### ISSUE THREAD

**Issue by sascha-kaufmann** [scenarioo/scenarioo#662]
Currently the ElasticSearchSearcher uses a TransportClient with hardcoded connection to localhost:9300 and does not apply the configuration in the config.xml file.

**Comment by sascha-kaufmann** [comment]
Already pushed a fix for it and waiting for the build to complete :)

**Comment by bruderol** [comment]
@sascha-kaufmann what? really? unbelievable that nobody never reported that? how did that go into there? Tahnks for correction!

**Comment by eggerschwiler** [comment]
@sascha-kaufmann can this issue be closed?

**Comment by bruderol** [comment]
I think yes. Thanks @sascha-kaufmann for fixing it!
