### ISSUE TITLE
Update documentation regarding CI

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#666]
This page has an outdated section regarding new branches and the image about the build pipeline should be updated to match the new Jenkins pipeline.

https://github.com/scenarioo/scenarioo/blob/develop/docs/contribute/Build-Server.md

**Comment by bruderol** [comment]
Yes, indeed :+1:

**Comment by bruderol** [comment]
@adiherzog I assigned it tou our technical debts, since it is not release related - I propose to use the milestone "Technical Debts" for all such things which is A not a feature and B we have to improve but is not blocking or related to a release.

**Comment by adiherzog** [comment]
@bruderol Why should we use a milestone for this? I think a label would be more suitable. And I think "technical dept" is not necessary. More important is the topic (documentation) and the priority, which is already set.

**Comment by bruderol** [comment]
@adiherzog let's discuss tomorrow. Thanks

**Comment by adiherzog** [comment]
I updated the documentation. I left the image but added a note that it's not exactly the same anymore with Jenkins Pipelines.
