### ISSUE TITLE
Update documentation regarding Development Environment Setup

### ISSUE THREAD

**Issue by eggerschwiler** [scenarioo/scenarioo#667]
This page is outdated:
http://scenarioo.org/docs/contribute/Development-Environment-with-IntelliJ.html
I encountered the following errors when going through the guide:
- the artefact is called scenario-viewer
- for scenarioo Gradle JVM has to be 1.8

**Comment by bruderol** [comment]
@eggerschwiler you mean `scenarioo-viewer` ? ;-)

**Comment by eggerschwiler** [comment]
Docu was updated with pull request #667.
