### ISSUE TITLE
Comparison configurations with regexp for base branch

### ISSUE THREAD

**Issue by mi-we** [scenarioo/scenarioo#673]
As a user I want to be able to define comparisons for all feature branches against the develop branch.

# Acceptance Criteria

* Allow regular expressions for the base branch of a comparison configuration
* Pure branch names as base branch definitions like "feature/some-feature" should work as before

**Comment by bruderol** [comment]
Maybe a cool small task somebdoy could do, if he likes to ?

**Comment by bruderol** [comment]
I started to implement it - because I want to have it such that we can compare all feature branches against develop branch.

**Comment by bruderol** [comment]
done - see PR #715
