### ISSUE TITLE
Publish Documentation for each Release and Develop with Version Selection Dropdown

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#675]
E.g. using https://plugins.gitbook.com/plugin/versions

We should also build and deploy the documentation of the latest development version.

**Acceptance Criteria**
* Latest Master docu deployed here: http://scenarioo.org/docs/master/
* Develop Docu deployed here: http://scenarioo.org/docs/develop/
* Version 3.0 Docu deployed here: http://scenarioo.org/docs/3.0/
* Automated deployment of develop docu from develop branch on each push on Jenkins
* Automated deployment of master docu from master branch on each push on Jenkins
* Automated deployment of archived version docu from release/* branches on each push on Jenkins
* Documented how to deploy versioned docu for each release (currently manually)
* Adjusted links in all our repos and on webpage

**Comment by adiherzog** [comment]
@cgrossde I added a story for this with the link you sent me.

**Comment by bruderol** [comment]
@adiherzog ich würd das gerne noch vor dem nächsten Release lösen, damit wir die Docu sauber versioniert haben. Das verfolgt uns immer wieder.

**Comment by bruderol** [comment]
working on it --- will make current develop version available here: http://scenarioo.org/docs/develop

**Comment by bruderol** [comment]
Implemented and adjusted the story description with acceptance criteria how it is now implermented.

See PR #712
