### ISSUE TITLE
How to efficiently develop and debug server changes?

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#690]
I struggle with that currently ... 

We have to clarify what is a stable run configuration in our IDE to have the follow scenario work reliably:

* Build & Start server
* Make a small change in one class
* Hot deploy it (or at least have one well known reliable way to get a up and running server with changes again with one click as fast as possible)
* Debug / Test the changes

Current situation:
* It seems not to work reliably, that when I change something - and I do not even know whatwould be the right process ot follow

**Comment by bruderol** [comment]
@cgrossde @adiherzog Woudl be cool if we can improve current situation here - I am currently unsure what current state is about that. My setup does still not work well concernung that.

**Comment by bruderol** [comment]
I found and documented a possible solution - seems to work - I will test to work with that a little bit more and let you know whether that solves my problems.

**Comment by bruderol** [comment]
Advantage of the documented changes to my setup is that it always uses latest WAR (no problems when I update changes form the repo, name stays constant).

Disadvantage: Hot deployment of changes to classes seems not to work anymore - I always have to restart the server (CTRL+F9 trick seems not to work).

**Comment by eggerschwiler** [comment]
@bruderol While reworking the developer documentation I documented a setup that worked: https://github.com/scenarioo/scenarioo/blob/feature/688-rework-developer-documentation/docs/contribute/Developer-Guide.md#working-with-scenarioo. Does this work for you as well?
