### ISSUE TITLE
Add missing e2e tests for new Features in 4.0

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#698]
We introduced some new features in Release 4.0 that are not yet covered with e2e tests:

- [x] New Dialog "Create Comparison..."
- [x] New Management View for Comparisons
- [x] Dialog for Displaying Logs for Comparisons
- [x] Recalculating Comparisons

I think one simple scenario for each of the mentioned features would already be enough to get that basically covered..

See stories #650 , #692 and #604

**Comment by bruderol** [comment]
just for we not forget it - such that we can close the other stories and merge the PRs for now.

**Comment by bruderol** [comment]
@scenarioo/scenarioo-devs Maybe somebody havig time to write some protractor e2e tests?? might be cool task for somebody who never wrote one? its prety easy and you can simply look and see how we did the other tests and do it similar. You can ask me for help.

**Comment by eggerschwiler** [comment]
Will be closed once Pull Request #808 is reviewed and merged.
