### ISSUE TITLE
Improve wait for server startup after deployment (e.g. wait for log statement)

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#704]
Currently we just wait for a certain time (2 minutes?) which is not a very stable and makes builds unnecessarily long time blocking. 

Since It works pretty well at the moment though, so there's no high urgency to fix this.

**Comment by adiherzog** [comment]
Related to #703

**Comment by bruderol** [comment]
yes, would be useful to improve that. Thanks for opening!

**Comment by bruderol** [comment]
Assigned to myself. Want to get rid of this tech debt, also because it might help to get faster build feedback if during startup of scenarioo already something fails

**Comment by eggerschwiler** [comment]
Duplicate of #637 ?

**Comment by eggerschwiler** [comment]
Has been resolved with issue #637
