### ISSUE TITLE
Diff Viewer: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#719]
Sometimes some of the comparisons fail on the CI, with this error message:

```=== START OF BUILD COMPARISON ===
Comparison To most recent (dev) on target build wikipedia-docu-example-dev/2014-05-19 for comparing with build Development/most recent
Use Case wikipedia-docu-example-dev/2014-05-19/Donate has addedElements: 1 changedElements: 0 removedElements: 1 changeRate: 100.0
FAILURE on comparing build wikipedia-docu-example-dev/2014-05-19 with defined comparison: To most recent (dev)
           see following exception messages and stack trace: 
             > java.lang.OutOfMemoryError: Java heap space
             > 	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
             > 	at java.awt.image.Raster.createPackedRaster(Raster.java:467)
             > 	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
             > 	at java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
             > 	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:557)
             > 	at sun.java2d.loops.GraphicsPrimitive.convertFrom(GraphicsPrimitive.java:541)
             > 	at sun.java2d.loops.MaskBlit$General.MaskBlit(MaskBlit.java:189)
             > 	at sun.java2d.loops.Blit$GeneralMaskBlit.Blit(Blit.java:204)
             > 	at sun.java2d.pipe.DrawImage.blitSurfaceData(DrawImage.java:959)
             > 	at sun.java2d.pipe.DrawImage.renderImageCopy(DrawImage.java:577)
             > 	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:67)
             > 	at sun.java2d.pipe.DrawImage.copyImage(DrawImage.java:1014)
             > 	at sun.java2d.pipe.ValidatePipe.copyImage(ValidatePipe.java:186)
             > 	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3318)
             > 	at sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3296)
             > 	at org.scenarioo.business.diffViewer.comparator.ScreenshotComparator.compareScreenshots(ScreenshotComparator.java:103)
             > 	at org.scenarioo.business.diffViewer.comparator.ScreenshotComparator.compare(ScreenshotComparator.java:72)
             > 	at org.scenarioo.business.diffViewer.comparator.StepComparator.compareElementAndWrite(StepComparator.java:83)
             > 	at org.scenarioo.business.diffViewer.comparator.StepComparator.compareElementAndWrite(StepComparator.java:35)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.compareElementsAndWrite(AbstractStructureComparator.java:82)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.calculateDiffInfo(AbstractStructureComparator.java:69)
             > 	at org.scenarioo.business.diffViewer.comparator.StepComparator.compare(StepComparator.java:66)
             > 	at org.scenarioo.business.diffViewer.comparator.ScenarioComparator.compareElementAndWrite(ScenarioComparator.java:72)
             > 	at org.scenarioo.business.diffViewer.comparator.ScenarioComparator.compareElementAndWrite(ScenarioComparator.java:34)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.compareElementsAndWrite(AbstractStructureComparator.java:82)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.calculateDiffInfo(AbstractStructureComparator.java:69)
             > 	at org.scenarioo.business.diffViewer.comparator.ScenarioComparator.compare(ScenarioComparator.java:58)
             > 	at org.scenarioo.business.diffViewer.comparator.UseCaseComparator.compareElementAndWrite(UseCaseComparator.java:62)
             > 	at org.scenarioo.business.diffViewer.comparator.UseCaseComparator.compareElementAndWrite(UseCaseComparator.java:29)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.compareElementsAndWrite(AbstractStructureComparator.java:82)
             > 	at org.scenarioo.business.diffViewer.comparator.AbstractStructureComparator.calculateDiffInfo(AbstractStructureComparator.java:69)
             > 	at org.scenarioo.business.diffViewer.comparator.UseCaseComparator.compare(UseCaseComparator.java:48)
=== END OF BUILD COMPARISON (failed) ===
```

This leads to test failures:

http://build.scenarioo.org/jenkins/job/scenarioo/job/develop/90/

# Summary

* Elasticsearch 5 (running in docker) uses about 6 GB RAM while Elasticsearch 2 only used about 3.5 GB.
* We can switch off Elasticsearch 2, as it's not required on the develop branch anymore. This might make the situation better, but it might not be enough.

# Analysis

Memory usage at time of opening this bug (right after the build above failed):

      4594.69 Mb /usr/lib/jvm/jre -> Elasticsearch 5
      4428.58 Mb /usr/lib/jvm/java -> Tomcat
      4319.81 Mb /usr/bin/java -> Jenkins
      3400.34 Mb /usr/bin/java -> Elasticsearch 2
       552.64 Mb /usr/bin/dockerd
       416.06 Mb docker
       239.00 Mb /usr/bin/docker -> Elasticsearch 5
       216.48 Mb rsyslogd
        27.02 Mb /usr/bin/Xvfb :99
        26.13 Mb /usr/bin/docker
         8.65 Mb /usr/share/elasticsearch/plugins/x
         4.71 Mb docker

Memory after stopping Tomcat:

      4594.69 Mb /usr/lib/jvm/jre
      4319.81 Mb /usr/bin/java
      3400.34 Mb /usr/bin/java
       552.64 Mb /usr/bin/dockerd
       416.06 Mb docker
       247.00 Mb /usr/bin/docker
       216.48 Mb rsyslogd
        27.02 Mb /usr/bin/Xvfb :99
        26.13 Mb /usr/bin/docker
         8.65 Mb /usr/share/elasticsearch/plugins/x
         4.71 Mb docker

Memory after stopping Jenkins as well:

      4594.69 Mb /usr/lib/jvm/jre
      3400.34 Mb /usr/bin/java
       552.64 Mb /usr/bin/dockerd
       416.06 Mb docker
       247.00 Mb /usr/bin/docker
       216.48 Mb rsyslogd
        27.02 Mb /usr/bin/Xvfb :99
        26.13 Mb /usr/bin/docker
         8.65 Mb /usr/share/elasticsearch/plugins/x
         4.71 Mb docker

Memory after stopping Elasticsearch 5:

      3400.34 Mb /usr/bin/java
       552.64 Mb /usr/bin/dockerd
       416.06 Mb docker
       216.48 Mb rsyslogd
        27.02 Mb /usr/bin/Xvfb :99

Memory after stopping Elasticsearch 2:

       552.64 Mb /usr/bin/dockerd
       416.06 Mb docker
       216.48 Mb rsyslogd
        27.02 Mb /usr/bin/Xvfb :99

**Comment by adiherzog** [comment]
Executed this (from https://github.com/docker-library/elasticsearch/issues/111):

`sudo sysctl -w vm.max_map_count=262144`

Looks like this helped. Now elasticsearch5 runs for longer than just a few seconds. Scenarioo can find it. Develop build looks fine.

**Comment by adiherzog** [comment]
We have to observe whether it's more stable now (also with the PR from @bruderol that limits concurrent builds).

**Comment by bruderol** [comment]
@adiherzog Wow, aesome analysis! Seems you had a hard night ;-) 
I wanted to do that `sudo sysctl -w vm.max_map_count=262144` thing when I installed elasticsearch - but @cgrossde and me decided to not apply it as long as it runs like that and I didnt have the impression that recent problems had to do with elasticsearch. Sorry for that.

**Comment by bruderol** [comment]
Maybe we also have to analyse more deeply, whether we have a memory leak issue in comparisons. Are some resources when comparing screenshots forgotten to be freed?

**Comment by bruderol** [comment]
it happened again:
http://54.88.202.24/jenkins/job/scenarioo/job/feature%252F720-deploy-selfdocu-for-master-and-develop-to-both-demo-instances/3/

Out of Memory in Comparisons!

**Comment by bruderol** [comment]
@adiherzog By the way - after next release we can also remove GraphicMagick!

**Comment by bruderol** [comment]
@adiherzog Something is fishy on the elasticsearch engine now - I see a lot of errors like the following in the log:
```
java.lang.IllegalStateException: Received message from unsupported version: [2.0.0] minimal compatible version is: [5.0.0]
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1390) ~[elasticsearch-5.6.9.jar:5.6.9]
```

Did you configure the master demo to use elasticsearch 5 as well ??

**Comment by adiherzog** [comment]
@bruderol I removed elasticsearch from the config.xml of the master demo now. Hope this stops the error message.

**Comment by adiherzog** [comment]
@bruderol Yes, we need to further analyze the memory issue. Maybe we need a bigger swap partition or we have to change the configuration which application gets how much memory.

**Comment by bruderol** [comment]
@adiherzog 1. demo config is always restored on redeploying - 2. elasticsearch was configured under a different port - that is why i not understand it.

**Comment by adiherzog** [comment]
The values in the memory analysis above do not actually show how much memory is used. Seems this is a pretty complicated topic: https://stackoverflow.com/questions/131303/how-to-measure-actual-memory-usage-of-an-application-or-process

I did some changes to our memory configuration.

Jenkins is now limited to 2 GB, it was not explicitly limited before:

`JAVA_ARGS="-Xmx2048m -XX:MaxPermSize=512m -Djava.awt.headless=true"` in `/etc/default/jenkins`.

Tomcat now has 2 GB of memory instead of just 1 GB:

`JAVA_OPTS="-Djava.awt.headless=true -Xms1024m -Xmx2048m -XX:MaxPermSize=1024m -XX:+UseConcMarkSweepGC"` in `/etc/default/tomcat7`.

This seems to help, let's observe it.

**Comment by bruderol** [comment]
Thansk tousand! I think we can close that - if we not run into troubles anymore.
