### ISSUE TITLE
Migrate Scenarioo Application to Spring Boot Standalone Runner / Boot WAR

### ISSUE THREAD

**Issue by mi-we** [scenarioo/scenarioo#724]
# Goal
As part of the modernization, Scenarioo should become a sel-containing app. It was decided to use Spring Boot as a base.

# Acceptance Criteria
* [x] The Scenarioo viewer can be built as a runnable WAR file, e. g. scenarioo.war
* [x] The WAR is also still possible to deploy to a tomcat, if needed
* [x] The docker image is updated to run scenarioo as standalone and not to contain tomcat installation anymore.
* [x] The REST interfaces are utilizing Spring technologies, not JAX-RS anymore
* [x] The CI tests e2e tests against spring boot standalone runner (or docker image)
* [ ] The build import rest endpoint is secured with spring security, see #778
* [ ] Documentation is updated
* [ ] Any breaking changes are documented:
  * changelog with link to migration guide
  * migration guide with links to relevant docu sections

# Open Points
- Handling of security constraint from web.xml (Spring alternative)
-- How can the credentials be defined for the Docker image?
- Documentation:
-- Development Setup with Spring Boot
- Possible problem with FAT-WAR, exception on startup, "URI is not hierarchical"

**Comment by eggerschwiler** [comment]
Leider auf Jenkins immer noch Probleme mit npm, obwohl es auf Develop 10 Stunden vorher funktioniert hat:
"./ci/runE2ETests.sh: line 28: npm: command not found"

**Comment by eggerschwiler** [comment]
Access Log works as before if the war is used in an existing Tomcat.
If the fat-war is used, then the access log can be configured in application.properties. Details are in the docu (Scenarioo-Viewer-Web-Application-Setup.md)
