### ISSUE TITLE
Build Import: UI issues

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#727]
# Import error message not cleared

## Impact

Small, cosmetic issue that might lead to confusion.

## Steps

- Import build that runs in to import status "FAILED" (e.g. put a text file into the step folder that can't be deserialized).
- Remove the problem that makes the import fail
- Reimport
- Open import dialog -> The error message from the failed import is still shown. It should be cleared though.

![image](https://user-images.githubusercontent.com/3780183/41654399-a6a17528-7489-11e8-9a2b-67a25039512e.png)

# Don't show number of use cases / scenarios if not known yet

In state "PROCESSING" we should not show the number of use cases and scenarios yet in the Builds view

![image](https://user-images.githubusercontent.com/3780183/41702526-b3b92344-7530-11e8-9818-383f29425524.png)

**Comment by bruderol** [comment]
@adiherzog I removed the “bug” label. While I agree this is not optimal, I think it is no bug. Read about “Zero Bugs” if you not agree ;-)
See https://medium.com/qualityfaster/the-zero-bug-policy-b0bd987be684

**Comment by mi-we** [comment]
Reconsidered this issue with @bruderol and we agreed that the first part indeed is a small bug, that we should remove - the error log message from last failure seems not to get cleaned away. to be fixed for next release if doable.

**Comment by bruderol** [comment]
I could not reproduce - I had a failing build (dont know why) - and after reimport I did not see the error anymore.Might need further clarification.

**Comment by eggerschwiler** [comment]
I was able to reproduce it yesterday. The error message is visible as long as the reimport is still in the state PROCESSING. It disappears once the reimport is successful.
