### ISSUE TITLE
TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#733]
Just before the JS unit tests run we see this error message:

```
01:13:17 ERROR in /var/lib/jenkins/jobs/scenarioo/branches/feature-headless-chrome.g70h4c/workspace/scenarioo-client/test/e2e/specs/manage_branch_aliases.ts
01:13:17 [tsl] ERROR in /var/lib/jenkins/jobs/scenarioo/branches/feature-headless-chrome.g70h4c/workspace/scenarioo-client/test/e2e/specs/manage_branch_aliases.ts(14,20)
01:13:17       TS2705: An async function or method in ES5/ES3 requires the 'Promise' constructor.  Make sure you have a declaration for the 'Promise' constructor or include 'ES2015' in your `--lib` option.
```

Example: http://build.scenarioo.org/jenkins/job/scenarioo/job/feature%252Fheadless-chrome/1/consoleFull

**Comment by bruderol** [comment]
@adiherzog broken window syndrome - we have to get rid of this.

In future we should let the build fail on such errors!

**Comment by bruderol** [comment]
Looking at the error message it might be that just the tsconfig.json in test/e2e dir is not optimal for our e2e tests yet! Adding “es2017” to lib could maybe help? See also similar change here for our client typescripts maybe: https://github.com/scenarioo/scenarioo/pull/745/files#diff-f4ccb31c2b259002fb085d41babb22a9

**Comment by cgrossde** [comment]
Fixed it on the `feature/724-spring-boot-migration` branch. As @bruderol mentioned we were missing `ES2015` and `DOM` under `lib` in `tsconfig.json`. => 6ffa24eaa4dfbc09fb10ca4775619c8bb778bc6e 

What does `lib` do?

> with --lib you can specify a list of built-in API declaration groups that you can chose to include in your project. For instance, if you expect your runtime to have support for Map, Set and Promise (e.g. most evergreen browsers today), just include --lib es2015.collection,es2015.promise. Similarly you can exclude declarations you do not want to include in your project, e.g. DOM if you are working on a node project using --lib es5,es6.

**Comment by bruderol** [comment]
@cgrossde awesome !! Thanks for taking care and closing this!!

**Comment by xgqfrms** [comment]
# How to fixed TypeScript Promise Error

> just need to add a line of code`"lib": ["es2015"],` in your `tsconfig.json`

```js
{
   // ...
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["es2015"],// ✅
    // ...
  }
}

```
