### ISSUE TITLE
Automated tests for new public comparison REST API

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#742]
Acceptance criteria

*  automated tests for diff viewer rest endpoints as documented in docu to ensure this functionality does not get broken in future releases

Follow up task from #605

**Comment by bruderol** [comment]
@adiherzog having more and more features without tests starts getting a risk for future releases

**Comment by bruderol** [comment]
I think this could be done easily as a spring rest controler test, similar to another test @mi-we did to test the spring security ??

**Comment by mi-we** [comment]
@bruderol That is right, there is a Spring Boot test now for the Builds Resource. The test can be found here: `org.scenarioo.rest.builds.BuildsResourceIntegrationTest`
