### ISSUE TITLE
Replace feature branch testing on jenkins by new circle ci

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#769]
Now that we have circle-ci in place we want to get rid of needless overhead on our jenkins in a first priority at least for feature branches.

Acceptance criteria

* the new circle ci should at least also cover following things:
   * deploy scenarioo self docu reports (also on test failures) to develop demo
      * use different prefix in branch names to avoid conflicts with still running jenkins builds, e.g. "scenarioo-ci-"
   * do proper healthcheck of the server deployment (wait for all data successfully imported) and fail fast in case of failure before running the tests (for better stability and not running builds longer than needed when the startup or import already failed)
   
* jenkins ci for branches having the new spring boot migration and circle-ci integration done is adjusted as follows:
     * it only runs for release, develop and master branches and special branches with a special tag like ‘—demo’ in the branch name (this should help to limit the number of demo deployments and related tomcat stability problems)
     * for those branches it still does demo deployments to tomcat (as today)
     * (maybe only later:) it uses the artifacts from circle ci for these deployments 
     * either it still runs e2e tests after the demo deployment or alternatively at least some smoke tests of the server (see healthcheck above)
     * it still cleans up docu data (to remove old branches and old builds to not run out of disk space)

* scenarioo reports of e2e tests for develop and master will still be deployed to master demo AND develop demo!

* jenkins ci still works as before for old branches (release 4.0)

**Comment by bruderol** [comment]
@cgrossde i tried to summarize the discussion at the beer tonight of how we could move forward in this topic. You could maybe close your other story and continue on this one here. For your other even more advanced ideas I recommend to open further stories.

The here proposed design would reduce the load on our jenkins/demo server already a lot and we can then proceed with the more advanced ideas later. 

You agree?

**Comment by cgrossde** [comment]
This is great, thanks for summarizing

**Comment by bruderol** [comment]
@cgrossde just a hint: we have to use different prefix for branch names when generating docu data on circle ci, to avoid conflicts with docu generated on jenkins. I added this to the acceptance criteria.

**Comment by cgrossde** [comment]
Efforts will continue in #775 - Outcome of scenarioo day october
