### ISSUE TITLE
Spring Security for REST Endpoints 

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#778]
As application admin of Scenarioo I want to be still able to configure some users (username and password) also with new spring boot security mechanism in Scenarioo 5.0, such that the REST endpoints with write access can be secured.

**Acceptance Criteria**
* [x] One user and password can be configured to secure the build publishing endpoint
* [x] Requests to such secured REST endpoints are blocked, if no valid user is provided
* [x] Currently this is done only for the calls where we had a role defined before: probably only the build import REST endpoint
* [x] Per default these endpoints are secured with a random user name and password unless configured explicitly
* [x] How to configure fix usernames and passwords is documented well
  * [x] for spring boot setup
  * [x] for WAR deployment
  * [x] for docker setup
* [x] the breaking change is mentioned in changelog and shortly in the migration guide for version 5.0 (with link to the documentation)
* [x] it must be ensured that on the demo the same username and password is still configured for all demos (fix, not random, since used in other places, e.g. self-demo deployment)
* [x] tests that check
       * the call fails (e2e test) without correct user/pasword
       * the call succeeds with correct user/password

**Comment by mi-we** [comment]
@bruderol If ok for you, I will close this issue once the PR with the documentation updates has been merged

**Comment by mi-we** [comment]
@bruderol Please review and close

**Comment by eggerschwiler** [comment]
No open points remain, so I close this issue.
