### ISSUE TITLE
Self Docu Upload broken due to spring boot migration

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#787]
Self docu upload in our own ci does not work anymore after spring boot migration.

Build upload returns 500 internal server errror.

Acceptance criteria
* test added to reproduce
* problem fixed

Relates to https://github.com/scenarioo/scenarioo/issues/724

**Comment by bruderol** [comment]
I will try to fix it tomorrow.

Important because currently all builds fail because of this bug when uploading self docu

**Comment by eggerschwiler** [comment]
Issue resolved.
