### ISSUE TITLE
Builds state not calculated properly on import anymore with spring boot

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#792]
Seems like there is something broken with build states after spring boot migration.

How to reproduce:
1. Go here: 
http://demo.scenarioo.org/scenarioo-develop/#/?branch=Production&build=most%20recent&tab=usecases&comparison=Disabled
2. See under details of the build, that it has state ‘null’ 
3. Go to same url on master and see that there all builds got a calculated build status for each build.

**Comment by bruderol** [comment]
@mi-we @eggerschwiler I found this bug during a detailed demo session for our new student.

**Comment by eggerschwiler** [comment]
It looks like it fixed itself.

When I checked this morning, build 321 of scenarioo-feature-778-spring-endpoint-security is in status PROCESSING, even though the log says it has finished. The following builds (including the production one you link to) are QUEUED_FOR_PROCESSING.

I clicked REIMPORT on one of the queued builds and after a couple of minutes all builds were in a valid state.

@bruderol: Should we dig deeper?

**Comment by eggerschwiler** [comment]
@bruderol and @eggerschwiler had a look at this.

We think it might have to do with the way we deploy the application to the Demo Server (including Demo Data). Probable Solution: Clean demo data before deploying (beware: only wikipedia demo-data).

Reason: wikipedia demo-data has build status null, which leads to an automatic calculation on first import. However, when the app is newly deployed, the import data is already there so no import happens.

**Comment by eggerschwiler** [comment]
Was fixed in scenarioo-infrastructure (https://github.com/scenarioo/scenarioo-infrastructure/pull/9)
