### ISSUE TITLE
Always place cursor in search field

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#80]
When navigating to a new page, the search field should have the focus so that the user can instantly start a search by just typing the search term.

This applies to all pages that have a search field:
- Use Case list
- Scenario list
- Scenario details

**Comment by bruderol** [comment]
@mi-we As you are currently working on keyboard stuff, maybe you could also have a look at this?

**Comment by bruderol** [comment]
@adiherzog @danielsuter maybe we can improve such usability things when we rebuild that pages in angular X ?

**Comment by bruderol** [comment]
@SteffiSchlumpf maybe something you can solve?
