### ISSUE TITLE
Preparation Release 5.0: Prepare and Review Documentation, Migration-Guide, Changelog and Release-Notes

### ISSUE THREAD

**Issue by mi-we** [scenarioo/scenarioo#804]
* [x] Documentation and migration guide is updated and reviewed 
* [x] Any breaking changes are documented:
  * changelog with link to migration guide
  * migration guide with links to relevant docu sections
* [x] prepare release notes
* [x] integrate newest scenarioo-js version
* [x] Build Final Release Package
* [x] Build Docker Image and Publish to Dockerhub
* [x] Publish the Release on Github
* [x] promote release on Twitter, Yammer, etc.

**Comment by eggerschwiler** [comment]
Release has been finalized and promoted on Twitter and Yammer.
