### ISSUE TITLE
Provide development artifacts for download again

### ISSUE THREAD

**Issue by mi-we** [scenarioo/scenarioo#871]
# Problem
Since the migration to CircleCI, it is not possible anymore to download the WAR files from the latest develop and feature branch builds, if the user is not logged in on CircleCI. Before, one could download them via a direct link to the respective Jenkins build. This needs to be fixed.

It could also be possible to provide the latest artifacts via our demo server, for example. It is not yet clear if CirlceCI can provide similar functionality like Jenkins (pointing to the latest successful build, providing artifacts on the build overview)

# Acceptance criteria
- It is possible to download the WAR file from the latest develop branch build
- It is possible to download the WAR file from the latest builds of the feature branches
- The user does not have to be logged in on CircleCI for downloading the artifact
- The documentation is updated with the new download links. (`docs/downloads-and-links.md`)

**Comment by eggerschwiler** [comment]
CircleCI has an open feature request for this: https://discuss.circleci.com/t/referencing-latest-build-artifacts/931

The easiest way is to add a download link to the overview page. In this way we have a permanent download for develop and download links for the 4 most recent feature branches.
