### ISSUE TITLE
use standard jpeg content type in resources

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#897]
before the content type was "image/jpeg" - and i think this would be more correct - according to https://stackoverflow.com/questions/33692835/is-the-mime-type-image-jpg-the-same-as-image-jpeg

@sascha-kaufmann @eggerschwiler

_Originally posted by @bruderol in https://github.com/scenarioo/scenarioo/pull/893/review_comment/create_

**Comment by eggerschwiler** [comment]
@bruderol good point. After changing this I went one step further and swapped out one of the pngs with a jpeg image and noticed that the getScreenshot method doesn't work for jpeg images on IE 11. Duplicating the method did the trick. I tested both png and jpeg images on the following browsers:
* IE 11
* Edge
* Chrome
* Firefox
In the pull request I added a link to the Demo where this can be verified.

**Comment by bruderol** [comment]
It's awesome I just think we should improve the testing (demo data for jpeg and E2E tests) for this.

Thanks.

**Comment by eggerschwiler** [comment]
Added issue #905 for E2E/integration tests

**Comment by eggerschwiler** [comment]
additional technical corner case with jpeg image added to wikipedia example.
