### ISSUE TITLE
Application Info Popup disappears if query parameters were not provided

### ISSUE THREAD

**Issue by eggerschwiler** [scenarioo/scenarioo#900]
When accessing the website for the first time an application information popup appears.

However, when the address entered into the address bar does not contain query parameters, e.g. http://demo.scenarioo.org/scenarioo-master/ then the application information popup is only visible for a split second, because Scenarioo adds the standard query parameters to the address, which leads to a page reload. And since this is then treated as the second visit, the popup doesn't appear again.

**Comment by bruderol** [comment]
done ??

**Comment by eggerschwiler** [comment]
Fixed on release branch.
