### ISSUE TITLE
Remember collapsed /expanded state of detail accordeon

### ISSUE THREAD

**Issue by SteffiSchlumpf** [scenarioo/scenarioo#946]
Remember and preserve expansion/collapse state of the different detail-accordions while navigating. E.g. in the old version I could collapse labels and expand webtest class in scenarios overview and it would be the same if I navigated to a different scenario.

**Comment by eggerschwiler** [comment]
When this is implemented the following two tests need to be updated:
1. the commented out assert in the Test "Fallback to best match - Step - View" (step_view.ts) should be reactivated
2. The test "Metadata with link to object - Step View" (step_view.ts) should be enabled (xit -> it)
