### ISSUE TITLE
Make responsive navigation usable on mobile devices

### ISSUE THREAD

**Issue by adiherzog** [scenarioo/scenarioo#99]
When using Scenarioo on a phone, the navigation collapses, but it can't be opened, because the JavaScript is missing. Hope we find the code here: http://angular-ui.github.io/bootstrap/

**Comment by mi-we** [comment]
@adiherzog Is this still relevant? Looking at the demo server just now from my phone it seems we have a much bigger problem with the overall user experience of the viewer application.

**Comment by adiherzog** [comment]
@mi-we I think we can close this as we don't support phones.
