### ISSUE TITLE
Make docu build work with plant uml integration in gitbook

### ISSUE THREAD

**Issue by bruderol** [scenarioo/scenarioo#998]
Acceptance criteria
* the documentation build on circle ci is working with changes on branch of PR #995 (new UML diagrams in gitbook docu)
* the new diagrams are rendered nicely in our documentation on this page here: 
* PR #995 is reviewed and merged

Implementation Details / Hints
* Probably a special docker image is needed with graphvis installed to run the docu build with the plantuml plugin for gitbook
* the build job definition is located here: https://github.com/scenarioo/scenarioo/blob/develop/.circleci/config.yml#L173
* for testing the branch filter of the ci workflow can be changed in the workflow definition here: https://github.com/scenarioo/scenarioo/blob/develop/.circleci/config.yml#L273
* maybe this docker image setup discussed here is something similar to what we might need: https://blog.frankel.ch/layering-docker-images-dependencies/
* The additional plugin requirements here mentions to manually install PlantUML - as mentioned here: https://www.npmjs.com/package/gitbook-plugin-uml#additional-requirements  
But somehow I had not to do this to make it work locally - all I needed to have was graphviz installed on my windows machine.

**Comment by bruderol** [comment]
grösste herausforderung dürfte sein ein passendes docker image zu finden das auf Circle CI funktioniert oder selber eines zu bauen (basierend auf dem aktuell verwendeten zusätzlich mit graphviz ergänzt).

**Comment by lynparbone** [comment]
I've created a Dockerfile that assembles an image for circleci and installs graphviz version 2.38 and java 8 (this is necessary for graphviz to work). I compared with [this description](https://www.npmjs.com/package/gitbook-plugin-uml#additional-requirements) Rolf mentioned above. It was possible to build and use the image without the plantuml.jar, so I did not include it in the image setup.

**Comment by lynparbone** [comment]
I've pushed the image to the scenarioo docker repository and set the version to 1.0.0: https://hub.docker.com/r/scenarioo/circleci-with-graphviz
It is now used in the circleci configuration for the publish_docs job. The docu now displays UML images!
--> http://scenarioo.org/docs/umldocu/features/details/Details.html

Once reviewed and merged, I'll update the documentation [here](http://scenarioo.org/docs/umldocu/contribute/Documentation-and-Webpage.html) and mention the usage of this image. I'll add a short description to the image on docker hub as well.
